using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

#pragma warning disable CA1814 // Prefer jagged arrays over multidimensional

namespace SGE.Infrastructure.Migrations
{
    /// <inheritdoc />
    public partial class AddDynamicTextTable : Migration
    {
        /// <inheritdoc />
        protected override void Up(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.CreateTable(
                name: "dynamic_texts",
                columns: table => new
                {
                    Id = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    Code = table.Column<string>(type: "nvarchar(450)", nullable: false),
                    Text = table.Column<string>(type: "nvarchar(max)", nullable: false),
                    Description = table.Column<string>(type: "nvarchar(max)", nullable: true)
                },
                constraints: table =>
                {
                    table.PrimaryKey("PK_dynamic_texts", x => x.Id);
                });

            migrationBuilder.InsertData(
                table: "dynamic_texts",
                columns: new[] { "Id", "Code", "Description", "Text" },
                values: new object[,]
                {
                    { "01J4G2Z4XT00E8WYBBTQW6ZKDS", "ExplanationAdministrationGrid", null, "En esta sección podrá consultar o crear antenas y equipos y consultar reportes sobre información técnica y administrativa" },
                    { "01J4G2Z4XT011Y2NH3NQVN7VF8", "EmailAne2", null, "No disponible" },
                    { "01J4G2Z4XT025GAV997C74491F", "CorreoCopiaANE-MINTIC_Satelital", null, "Solicitudesdeespectro@g.com" },
                    { "01J4G2Z4XT02A4MX2G0D7GEYNR", "DestinatariosBCCDesestimientoTacitoSatelital", null, "soporte.sge@tesamerica.com.co" },
                    { "01J4G2Z4XT02VDQ7X66VP2MATK", "EspTemp_Hojas_Archivo_Tecnico", null, "1. Admin,2. Info General,3. IMT o PMP,4. Punto a Punto,5. Control de Cambios,Menu" },
                    { "01J4G2Z4XT06FGX7BN24KJWWK3", "Satelital_Portada_ANE", null, "Agencia Nacional del Espectro;Solicitudesdeespectro@g.com" },
                    { "01J4G2Z4XT0ABRJYXT5ZSYRHKH", "CorreoCertificadoRemitenteCargo", null, "Representante Legal" },
                    { "01J4G2Z4XT0ENDDYAWZDMGZ47D", "AlertBeforeDeleting", null, "Señor usuario" },
                    { "01J4G2Z4XT0JEGP2FHPC11AKJ0", "AZDigital_Resoluciones_Dependencia", null, "100" },
                    { "01J4G2Z4XT0PARX3526280K11P", "FirmaElectronicaAZRol", null, "F" },
                    { "01J4G2Z4XT0SMQ68YPSQB2G3AB", "TextoDetalleAlfaAnalisisTecnico", null, "Notificación de Aprobación de Análisis Técnico de la Solicitud: {0}" },
                    { "01J4G2Z4XT0SXBN16MPZ6FVSPX", "EspTemp_Fecha_Subsanacion_Admin", null, "1" },
                    { "01J4G2Z4XT0XMQ42DKSJM2N15K", "Temp_File_Satelital", null, "C:\\SAGE\\SGE\\tempdatafile" },
                    { "01J4G2Z4XT0YYHG3PPFH5RX7VP", "AZDigital_DependenciaSatelital", null, "2.2.0.1" },
                    { "01J4G2Z4XT10K1JPP7WMKGSN0M", "EstadosExpedienteNoUsadosCesion", null, "eRES,eCT,eBDU,eDEP,eIN,eREG,eVEN,eTER,eX0,eX1,eX1B,eX2B,eX3,eX4,eX4B" },
                    { "01J4G2Z4XT12ZDA85CNNC5P8G5", "CertificacionCarteraTextoFirma", null, "Coordinadora GIT de Cartera" },
                    { "01J4G2Z4XT1418M2SA0R524DPQ", "ExplanationAntennaList", null, "Seleccione la antena desde la lista de selección para ver los detalles. Si la antena no se encuentra puede crearla haciendo clic en el botón 'Nueva antena'" },
                    { "01J4G2Z4XT1450WRT5XA39V8BB", "CorreoInformeEvaluacion", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XT1DNBR7KEEM17V395", "MensajeBloqueoGarantias", null, "Señor usuario" },
                    { "01J4G2Z4XT1FS71ZTPGNFFNK9J", "CityCodeAne", null, "11001" },
                    { "01J4G2Z4XT1K7TH4860J6X3SJR", "EmailFinalizada", null, "soporte.tesamerica@tesamerica.com.co" },
                    { "01J4G2Z4XT1NVBAHQ5QS3JJHET", "CorreosAlertaCancelaciones", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XT1QJ7RHT7F6AH03ZQ", "CorreoCopiaANE", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XT1RM1KDTFZ3JRS3KP", "Fecha_Subsanacion_Revisor_Satelital_Administrativo", null, "1" },
                    { "01J4G2Z4XT1SM3KJ9RZEVTEE3Q", "TechnicalInformationSummaryNetworkNumber", null, "Red número:" },
                    { "01J4G2Z4XT20M81X1Z55AWSZHC", "ExplanationApplicationInProccess", null, "Se listan las solicitudes que aún no han sido radicadas oficialmente en el sistema." },
                    { "01J4G2Z4XT23CVHPCEDKDTB1VT", "ApproveAdministrativeAnalisisSerieDocumental", null, "Serie Documental" },
                    { "01J4G2Z4XT24TWY12XQGHVK5Z4", "ExplanationPortfolioEdit", null, "Desde este formulario es posible modificar el nombre del expediente correspondiente al expediente seleccionado" },
                    { "01J4G2Z4XT29EBG2X9R7VJZQSE", "FirmaElectronicaAZCodificacion", null, "Base64" },
                    { "01J4G2Z4XT29KPAJ3WTEJB4AWR", "FilesNeededToRadicate", null, "los tipos de archivos obligatorios para radicar una solicitud en un proceso de selección objetiva son: Formato Básico de la Solicitud (firmado por el representante legal)" },
                    { "01J4G2Z4XT2A8DX69PHQNP20FA", "EspTemp_CorreoRadicarANE", null, "Solicitudesdeespectro@g.com" },
                    { "01J4G2Z4XT2C7X17AGXCRF258Y", "DiasRevisionRadicadosAlfa", null, "30" },
                    { "01J4G2Z4XT2CG8E78SSZA4D7JP", "ExplanationApplicationCreation", null, "Por favor ingrese la información requerida para crear una nueva solicitud" },
                    { "01J4G2Z4XT2MANNT8T02C7DNTV", "EspTemp_AZDigital_TramiteRadicado", null, "PQRSD" },
                    { "01J4G2Z4XT2SDZX6H35BZ35X5S", "WfTipoAlfa", null, "0" },
                    { "01J4G2Z4XT2SEBVMBH7GNGSVZ0", "ResumenTecnicoTexto", null, "En virtud de la(s) solicitud(es) de [TipoTramite_NumRadicado]" },
                    { "01J4G2Z4XT2WQMARTD804TG35F", "IMT_RadioBusquedaMetros", null, "2600" },
                    { "01J4G2Z4XT2X4ZC2D4FWHHWQKW", "TextoDetalleAlfaRadicacion", null, "Radicación de la Solicitud: {0}" },
                    { "01J4G2Z4XT2Z97PP8EDBJRE6AQ", "SubdirectorIndustria", null, "gperdomo" },
                    { "01J4G2Z4XT2ZQ6B04VJRH8ED04", "RolesPermisoRevisionResoluciones", null, "2,3,4,5,6,7,22,57,59,60,61,62,76,77,78,79,99,100,108" },
                    { "01J4G2Z4XT2ZSEPXYXG3SC66CM", "FirmaElectronicaAZUsuario", null, "20201209-092929-982602-00332255" },
                    { "01J4G2Z4XT3499DRE0B2BKMM53", "TiposResolucionRenovacionOtorga", null, "1" },
                    { "01J4G2Z4XT35CB650HVDRQS6YG", "TextoDetalleAlfaRechazoSolicitud", null, "Notificación de Rechazo de la Solicitud: {0}" },
                    { "01J4G2Z4XT3899BX7EEVNRH5R4", "CorreoEnvioANE-Mintic", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XT38T0CWB75Y3TAT31", "NombreArchivoAlfaAnalisisAdministrativo", null, "Registro_Fin_Analisis_Administrativo_Solicitud_{0}_{1:ddMMyyHHmmss}.rtf" },
                    { "01J4G2Z4XT3A9HBFQ2YF44WNDW", "FirmaElectronicaAZTipoMime", null, "application/pdf" },
                    { "01J4G2Z4XT3D8BAEW9ZYK4K0J1", "xmlnsazs", null, "http://www.analitica.com.co/AZSign/Esquemas" },
                    { "01J4G2Z4XT3D9B8JE1VRKZ0H9V", "NombreArchivoAlfaRechazoSolicitud", null, "Rechazo_Solicitud_{0}_{1:ddMMyyHHmmss}.pdf" },
                    { "01J4G2Z4XT3EGGVWTYSVRQC6NZ", "NombreArchivoAlfaClosing", null, "Aprobacion_Final_Solicitud_{0}_{1:ddMMyyHHmmss}.rtf" },
                    { "01J4G2Z4XT3G914YAGADN236CW", "CorreosRechazoSolicitudMINTIC", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XT3HR26RPQHBNBWMA2", "MensajeBloqueoRTIC", null, "Señor usuario" },
                    { "01J4G2Z4XT3KMEZ4BS2PWW74KT", "EspTemp_TextoReqPorAnexoTec", null, "Anexo Técnico para permisos temporales: Para agilizar la evaluación técnica de la solicitud en curso" },
                    { "01J4G2Z4XT3W5NVTK9VFST66GZ", "AlertBeforeRadicationAdicional", null, "Sr. Usuario" },
                    { "01J4G2Z4XT3ZMJR8E3HEQVWWTN", "EstadosExpedienteActivo", null, "eAUT" },
                    { "01J4G2Z4XT4BFRA1GKB4S43YDW", "CorreosCargaCT", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XT4F4RYPN996BAQ29N", "Satelital_FirmaElec_SubDirector", null, "lpineda" },
                    { "01J4G2Z4XT4FX5D3Y67B1HENX8", "FechaFinMantenimiento", null, "11/10/2023 23:00:00.000" },
                    { "01J4G2Z4XT4KRHBY9KCXJ3FHZG", "UrlFirmaElectronica", "URL de consumo para el servicio de firma electrónica", "https://azsign.analitica.com.co/WebServices/SOAP/" },
                    { "01J4G2Z4XT4NH9VKJ7BWBKY4F7", "AZDigital_Resoluciones_TipoNotificacionCorreo", null, "CE" },
                    { "01J4G2Z4XT4TJFVTXPBS08C8JY", "CorreoCertificadoDocumentosCodificacion", null, "Base64" },
                    { "01J4G2Z4XT4TJKTNMY9EG0JAG5", "TiempoTokenMatrizANE", null, "50000" },
                    { "01J4G2Z4XT4W6AHR3FXNDYSBEW", "CorreosCopiaOcultaRechazoSolicitud", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XT4ZSHER2J99NM0YV8", "TextoRefRadicadoAnalisisTecnico", null, "Resultado de Análisis Técnico de la Solicitud con radicado MINTIC No. {0} del {1}." },
                    { "01J4G2Z4XT540A7EAGS7DK90YB", "RolesPermisoRevisionOficio", null, "73,74,75,101,107" },
                    { "01J4G2Z4XT55DWW1C4D6TW6K5X", "Cronograma", null, "2" },
                    { "01J4G2Z4XT59Y9X3Q7RV5T3Q0J", "AZDigital_Sitio", null, "Prue" },
                    { "01J4G2Z4XT5ARVHG6PGQY5NXP2", "FirmaElectronicaNombre", null, "Prueba Documento AZSign PHP WS" },
                    { "01J4G2Z4XT5DXXRKRNMFJVS790", "CorreoCertificadoURL", "Link consumo para el servicio de Notificaciones (IntegraTIC)", "https://cert-integratic.mintic.gov.co/Notificaciones/WebServices/SOAP/" },
                    { "01J4G2Z4XT5FACPXVMWQQ9YNQ4", "ApiNotificaciones_Aplicacion", null, "TesAmerica" },
                    { "01J4G2Z4XT5HF0HP7ZG7A9NPWN", "EstadosRedesSolicitudCanFrecBB", null, "rAUT" },
                    { "01J4G2Z4XT5NKNBTEKGF5ZV9CY", "CorreoCertificadoUsuario", null, "20230922-132449-805237-73089455" },
                    { "01J4G2Z4XT5PEJH27REJZB3G0B", "MensajeAdvertenciaRTIC", null, "Señor usuario" },
                    { "01J4G2Z4XT5PNF73RZM86FJXBD", "CodigoDestinoMintic", null, "pru001" },
                    { "01J4G2Z4XT5Q6C03WMFMMMP3BY", "AutenticacionTMP_Pruebas", null, "https://pruebas.tesmonitorplanning.com/TesMonitorPlanning/TesMonitorPlanningWeb/index.html?ID=" },
                    { "01J4G2Z4XT60F36W0HMNNBW32A", "AZDigital_Dependencia", null, "Pru" },
                    { "01J4G2Z4XT665FG0G2H2YFW5F7", "ApproveTechnicalAnalisisNaturaleza", null, "770" },
                    { "01J4G2Z4XT6833TEZ61762ZK8Z", "UrlImportSpectrumE", null, "http://simulacion.ane.gov.co:8088/se/portal/ane/loginproc.php?" },
                    { "01J4G2Z4XT6DS0DP08WJMF501T", "UserAlfa", null, "usersage" },
                    { "01J4G2Z4XT6FPRJ32RJJR7EP50", "CorreoCertificadoRemitenteNombre", null, "Andres Rodriguez" },
                    { "01J4G2Z4XT6GSP0F95DW20SB0B", "EspTemp_AZDigital_Dependencia", null, "Pru" },
                    { "01J4G2Z4XT6KTG69ZG3E0ECBKH", "CorreoAprobacionResolucionRevisor5", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XT6QDHADZH5JTYB2KB", "CorreoCertificadoCanalesAsunto", null, "Prueba Email Servicio Notificaciones" },
                    { "01J4G2Z4XT6V4SZVN47ZPYA252", "ExplanationApplicationTechnicalAnalysis", null, "En el análisis técnico se efectuará un estudio detallado de la información técnica registrada para cada solicitud" },
                    { "01J4G2Z4XT6WK2J43QQDYHZJ1J", "AutenticacionTMP", "https://espectro-co.ane.gov.co/TesMonitorPlanning/TesMonitorPlanningWeb/index.html?ID=", "https://espectro-co.ane.gov.co/TesMonitorPlanning/TesMonitorPlanningWeb/index.html?ID=" },
                    { "01J4G2Z4XT6ZKCJBY4YF7MT81E", "NombreArchivoAlfaRadicacion", null, "Radicacion_Solicitud_{0}_{1:ddMMyyHHmmss}.xml" },
                    { "01J4G2Z4XT744Z6DNA7066ZJAH", "ExplanationDuplexerList", null, "Seleccione el duplexor desde la lista de selección para ver los detalles. Si el duplexor no se encuentra puede crearlo haciendo clic en el botón 'Nuevo duplexor'" },
                    { "01J4G2Z4XT74CZP6EGXQDBS5P7", "CorreoEnvioRadicarSatelitalANE-Mintic", null, "solicitudessatelital@g.com,Paola@g.com" },
                    { "01J4G2Z4XT7C636Y1BV3KG7TKA", "AlertBeforeClosingApproval", null, "Señor funcionario" },
                    { "01J4G2Z4XT7CZPNFFQVVXY42XE", "CorreosAlertaCesionExpediente", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XT7GFZSQ93FVXYPZS2", "RolesPermisoVerDocumentacionSolicitudesDirectas", null, "30,76,77,78,79,57,59,98,60,61,62,99,100,72,73,74,75,101,107,108" },
                    { "01J4G2Z4XT7JJ62WSRHF1GK671", "EmailAne1", null, "soporte.tesamerica@tesamerica.com.co" },
                    { "01J4G2Z4XT7M93P2XY0MG1ZRP3", "HeaderRUES", null, "CO-QA/GOB/MINTIC-0012/SISCD" },
                    { "01J4G2Z4XT7NVWJYTH7P0BDAQ9", "TextoDetalleAlfaAnalisisAdministrativo", null, "Notificación de Aprobación de Análisis Administrativo de la Solicitud: {0}" },
                    { "01J4G2Z4XT7P0K5CA08WXGERP3", "CorreoCertificadoContraseña", null, "2eca78d9b47f82705c9bbc5efe71cd95" },
                    { "01J4G2Z4XT7QSGQYVDZ3CT1WSZ", "CoordinadorPSO", null, "ogarzon" },
                    { "01J4G2Z4XT7VFSWT0PV0C91XRD", "EspTemp_CorreoRechazoANE-MINTIC", null, "solicitudesane@g.com" },
                    { "01J4G2Z4XT7VWGTCQ2CFPHP89J", "TextoDetalleAlfaClosing", null, "Notificación de Aprobación final de la Solicitud: {0}" },
                    { "01J4G2Z4XT7VX4SKB5AY3AS5BR", "RutaGetTokenRUES", null, "wsToken" },
                    { "01J4G2Z4XT84QGCSMKVJQRR1WQ", "CorreoAprobacionMINTIC-ANE_Satelital", null, "Solicitudesdeespectro@g.com" },
                    { "01J4G2Z4XT84S4HBDZVT8EA565", "ExplanationApplicationDetails", null, "Información básica de la solicitud" },
                    { "01J4G2Z4XT898VNQACE2NT8QWQ", "MailSmtpPort", null, "587" },
                    { "01J4G2Z4XT89E7SCVXWVR56K0E", "IMT_AZDigital_TramiteRadicado", null, "PQRSD" },
                    { "01J4G2Z4XT8NCKHY5GSNNDW71D", "TelefonoMintic2", null, "No disponible" },
                    { "01J4G2Z4XT8NNT2NZN9JZC5YZK", "xmlnsxsi", null, "http://www.w3.org/2001/XMLSchema-instance" },
                    { "01J4G2Z4XT8P098SMX68XHR2HC", "FaxMintic", null, "No disponible" },
                    { "01J4G2Z4XT8X5V7X7KTQGW8Q4R", "TelefonoAne2", null, "No disponible" },
                    { "01J4G2Z4XT8ZZYJ04KQY97NDW3", "ApproveTechnicalAnalisisSerieDocumental", null, "Serie Documental" },
                    { "01J4G2Z4XT92D9F7W1YN31BB16", "Columna_Potencia_BB", null, "R" },
                    { "01J4G2Z4XT92HMQ1X2C9BJG72R", "IMT_IdAntenna", null, "27374" },
                    { "01J4G2Z4XT92HWPA0M5BR575H6", "DireccionMensajeMaximoCaracteres", null, "En el anexo solo se pueden ingresar máximo 49 caracteres en la dirección de la estación." },
                    { "01J4G2Z4XT981DJH7ZD2KJP4HJ", "Temp_File_Espectro_New", null, "C:\\SAGE\\EspectroTemporal\\EspectroTemp_Back\\tempdatafile" },
                    { "01J4G2Z4XT99T651MZKVXTR97N", "CorreoEnvioANE-MinticNOPSO", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XT9BBB6WYPAY1HFM39", "ClasesExpedienteRTIC", null, "96,81,83,84,86,87,88,89" },
                    { "01J4G2Z4XT9CP4Y0N2XM8Z3D2S", "EspTemp_ClaseExpediente", null, "90" },
                    { "01J4G2Z4XT9EBN5KNW86GZYYN5", "ExplanationRejectApplication", null, "Por favor ingrese la información requerida para rechazar la solitud" },
                    { "01J4G2Z4XT9FYPFQ9FYK3HQQHY", "ApiNotificaciones_Url", null, "https://integratic.mintic.gov.co/Notificaciones/Webservices/SOAP/" },
                    { "01J4G2Z4XT9MV4AXECBYYMH0PW", "AZDigital_Resoluciones_ProcedeRecurso", null, "Rep10" },
                    { "01J4G2Z4XT9PT086S2X8VEC1XK", "CustomerFrontLegalInfo", null, "Es interés del Ministerio de Tecnologías de la Información y las Comunicaciones (TIC) la salvaguardia de la privacidad de la información personal del usuario obtenida a través del sitio web" },
                    { "01J4G2Z4XT9WBSEDHW93Q7YZ76", "MailDesarrolladorModuloResolucionesSinGarantia", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XT9WKGY9DG10HTP6VW", "RequiredFieldImageMessage", null, "Campo requerido" },
                    { "01J4G2Z4XT9ZN2KTFBG34RJXEA", "FirmaElectronicaAZTipoPDF", null, "PDF" },
                    { "01J4G2Z4XTA0ECMQHVA8N4ERV6", "Garantia_Subdirector", null, "Subdirector de Industria de Comunicaciones" },
                    { "01J4G2Z4XTA0YHN0C8CCY444QN", "EspTemp_PuntajeTramite", null, "50" },
                    { "01J4G2Z4XTA1BTZRSFN9FH44QH", "CorreoCertificadoAplicacion", null, "TesAmerica" },
                    { "01J4G2Z4XTA27867E5ZB3WG9DC", "ApiNotificaciones_Usuario", null, "20231218-163125-18a4c0-17460376" },
                    { "01J4G2Z4XTA2GX95328KE9NFW3", "MensajeDuranteMantenimiento", null, "El Ministerio de Tecnologías de la Información/Fondo Único de TIC informa que se encuentra realizando un mantenimiento al aplicativo desde <u>las {0} hasta las {1} Durante este mantenimiento los servicios no están disponibles.</u> Agradecemos su comprensión." },
                    { "01J4G2Z4XTA41R8B4HSD2624E8", "CorreoCertificadoRemitenteEmail", null, "silvia.mesino@analitica.com.co" },
                    { "01J4G2Z4XTA6XNH0680QNVM08Y", "TechnicalInformationSummaryNetworkCount", null, "Número de redes de la solicitud:" },
                    { "01J4G2Z4XTA7APYYX0VMQA5E7N", "ExplanationAntennaCreation", null, "Formulario de creación de antena" },
                    { "01J4G2Z4XTA7YZQ6T758J907M1", "DireccionMensajeFormato", null, "El formato para ingresar la dirección de la estación en el anexo es: Identificación de la vía (calle" },
                    { "01J4G2Z4XTA8N564H7CYZKKRRB", "ServicioRUES", "Link de consumo para el servicio RUES", "http://10.100.101.174/r1/CO-QA/GOB/CONFECAMARAS-0001/RUES/" },
                    { "01J4G2Z4XTAEEMKK0KXSXDJ9J1", "GrandTypeRUES", null, "password" },
                    { "01J4G2Z4XTAJ0831E3YNCAA2MY", "MotivoRechazoRUTIC", null, "No cumplir con lo establecido en el numeral 1 del artículo 3 de la resolución 485 de 2024" },
                    { "01J4G2Z4XTAM3C6HVY88C76NWA", "ExplanationTechnicalInformationSummaryNoInfo", null, "No se ha ingresado información técnica a la solicitud." },
                    { "01J4G2Z4XTAPS1JBHEP0DF881G", "CausaRechazoNOSubsanar", null, "No cumplir con lo establecido en el numeral 1" },
                    { "01J4G2Z4XTATJN3WS972MSGH2Z", "MensajeAdvertenciaCartera", null, "Señor usuario" },
                    { "01J4G2Z4XTB3AP8MK8MTZ1PSQM", "AZDigital_Resoluciones_UsuarioFirmante", null, "nalmeyda" },
                    { "01J4G2Z4XTB70YZ1M53SGH6K28", "Subdireccion_Industria", null, "gperdomo@mintic.gov.co" },
                    { "01J4G2Z4XTBB9ABDTFQXYJ90T7", "IMT_IdEquip", null, "17363" },
                    { "01J4G2Z4XTBBBAEGCS6QGE2RCB", "ExplanationApplicationInProccessFront", null, "Se listan las solicitudes que aún no han sido radicadas oficialmente en el sistema." },
                    { "01J4G2Z4XTBK22JK1XA4CSX7N8", "FirmaElectronicaAZOrden", null, "0" },
                    { "01J4G2Z4XTBNT716DF9W2X6R25", "EspTemp_CorreoAprobacionANE_MINTIC", null, "solicitudesane@g.com,ruben.zuleta@tesamerica.com.co" },
                    { "01J4G2Z4XTBQ8A49EHJVSG4PDK", "AZDigital_Resoluciones_TipoNotificacionFisico", null, "P" },
                    { "01J4G2Z4XTBR9G07365DZSN4PQ", "Fecha_Subsanacion_Coordinador_Satelital_Tecnico", null, "5" },
                    { "01J4G2Z4XTC0ZJF86201ZXZ1G1", "AZDigital_IdDirectorioConsultaPSO", null, "24828" },
                    { "01J4G2Z4XTC1E5D82RVYG4FW0M", "DestinatariosDesestimientoTacitoSatelitalpreliminarAne", null, "hernan.palta@tesamerica.com.co" },
                    { "01J4G2Z4XTC2K2Q9PM7TPQVNJR", "IMT_AZDigital_IdDirectorio", null, "132082" },
                    { "01J4G2Z4XTC5SC1CYB23PE8JJM", "CorreosSubsanacionOperador", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTCAMAXMBX1NB93N80", "xsischemaLocation", null, "http://www.analitica.com.co/AZSign/Esquemas file:///F:/AZSign/Producto/AZSign/WebServices/WS-AZSign.xsd" },
                    { "01J4G2Z4XTCBJ8GCX4DZRMKE8R", "DestinatariosCCDesestimientoTacitoSatelital", null, "" },
                    { "01J4G2Z4XTCBM0X3KSJJQPB885", "Clases_Expedientes_Satelital", null, "92" },
                    { "01J4G2Z4XTCBWMC3N7ZW8G2NDK", "EspTemp_PortadaMINTIC", null, "Ministerio de Tecnologías de la Información y las Comunicaciones; solicitudesane@g.com" },
                    { "01J4G2Z4XTCGYJ7XT3B1V4V7TJ", "EmailAnalisisAdministrativo", null, "soporte.tesamerica@tesamerica.com.co" },
                    { "01J4G2Z4XTCMY64NRD3FGCRESZ", "ExplanationFilesSummaryNoFiles", null, "No se han adjuntado archivos a la solicitud." },
                    { "01J4G2Z4XTCNRG8BVWKXN67XKZ", "CorreoCertificadoCanalesMensaje", null, "Mensaje del Email Pruebas" },
                    { "01J4G2Z4XTCQK8ZCMJ9JBPRCBF", "ExplanationApplicationDetailsArchivosSolDirectas", null, "Archivos necesarios: Cédula de ciudadanía" },
                    { "01J4G2Z4XTCSBD806EXYF1WPBF", "NumeroArchivosRadicacionSolDirecta", null, "9" },
                    { "01J4G2Z4XTCV19X7EJKNNPACGX", "MensajeAdvertenciaRTICDiferenciasNOPSO", null, "Señor usuario" },
                    { "01J4G2Z4XTCY6QHWKKKG6CKKA5", "AlertBeforeRadication", null, "Señor usuario: tenga en cuenta que una vez radicada la solicitud" },
                    { "01J4G2Z4XTCYEZ0B8S5ZMG2TMB", "CorreoEnvioAdjuntoRadicarSatelitalANE", null, "Solicitudesdeespectro@g.com,ruben.zuleta@tesamerica.com.co" },
                    { "01J4G2Z4XTD3JW14RQ1DBR42AB", "PasswordServicioAuraPortalNew", null, "1mp3rs0n4t3." },
                    { "01J4G2Z4XTD43V16FXCY12VY8D", "ApproveAdministrativeAnalisisNaturaleza", null, "770" },
                    { "01J4G2Z4XTD7CNZJTQ2471Y905", "ExplanationApplicationCertificados", null, "Por favor seleccione el tipo de certificado" },
                    { "01J4G2Z4XTD9356TKVM2781PF0", "CorreosRequerimientoTotalBB", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTD9FSZ3GRZPBW222N", "ExplanationApplicationRedes", null, "Por favor seleccione las redes del expediente seleccionado que desea incluir en el certificado." },
                    { "01J4G2Z4XTD9WGS9X2E1XN3KW7", "ExplanationApplicationEdit", null, "Puede asignar un nombre personalizado a esta solicitud" },
                    { "01J4G2Z4XTDFMWBV73C0G8N98R", "UsernameRUES", null, "UserMinTic" },
                    { "01J4G2Z4XTDN6S183VPVQZASX9", "DireccionMintic", null, "Edificio Murillo Toro Cra. 8a entre calles 12 y 13" },
                    { "01J4G2Z4XTDNCSNAH8NHPK9FAC", "ExplanationApplicationAdministrativeAnalysis", null, "El análisis administrativo de una solicitud es el primer proceso luego de su radicación." },
                    { "01J4G2Z4XTDQ2X8FT0RH9R50PZ", "RutaGetConsultaRUES", null, "wsConsultaRUES" },
                    { "01J4G2Z4XTDQVWVKJ2R841QCQV", "MainPattern", null, "[ .;,:¿?¡!(){}&%$_*+\\'''#|=º^¨~-]" },
                    { "01J4G2Z4XTDVTMY64EH6HDKZJW", "IdExpedienteIMT", null, "70974" },
                    { "01J4G2Z4XTDXQ47RJ8NAZ8A54S", "CorreosAletaBloqueos", null, "andres.rodriguez@tesamerica.com.co,bloqueos@g.com" },
                    { "01J4G2Z4XTDZC9G6J41JX3G8BA", "UrlLoginSpectrumE", null, "http://simulacion.ane.gov.co:8088/se/portal/ane/loginproc.php?" },
                    { "01J4G2Z4XTE2AAD2CNQ77D9SNP", "CertificacionGarantiasTextoFirma", null, "Coordinador GIT de Gestión de Garantías" },
                    { "01J4G2Z4XTE35WJAQ3012MZB28", "http://www.mintic.gov.co/", null, "http://www.mintic.gov.co/" },
                    { "01J4G2Z4XTE3V9F1K644XM029M", "PrivacyPolicy", "Ver el texto completo", "http://www.mintic.gov.co/index.php/privacidad-condiciones-uso" },
                    { "01J4G2Z4XTE4FE5PFJ0RGQZ9TA", "CorreosRadicacionSolicitudesPSO", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTE6H3SGTE16PH4HCQ", "AlertBeforeTechnicalAnalisisApprobation", null, "Señor funcionario" },
                    { "01J4G2Z4XTE8G7WDASJCPM7C0G", "CorreoCopiaMINTIC-ANE_Satelital", null, "solicitudessatelital@g.com,Paola@g.com" },
                    { "01J4G2Z4XTE9HDZJ5MATXNF0WV", "EmailCierre", null, "soporte.tesamerica@tesamerica.com.co" },
                    { "01J4G2Z4XTEBR9CRYRBFVM6EYB", "IMT_AZDigital_Sitio", null, "TL" },
                    { "01J4G2Z4XTEBXX7SC5T3Q7WAM5", "CorreosCreacionPSO", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTECMKPAY04YMR1KAV", "DestinatariosDesestimientoTacitoSatelital", null, "hernan.palta@tesamerica.com.co" },
                    { "01J4G2Z4XTEEHBXR4YRKDBH4TM", "FirmaElectronicaAZCuenta", null, "20201120-151412-85f600-89728214" },
                    { "01J4G2Z4XTEH34NZ462Z4WJMB4", "TiempoAutoguardadoMilisegundos", null, "300000" },
                    { "01J4G2Z4XTEH842XY9QS5ABKPJ", "CorreoCoordinacion_GGCCG", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTEMKVQBRX7FHK798B", "CorreoCertificadoDocumentosTipoMime", null, "application/pdf" },
                    { "01J4G2Z4XTEP922BYS8WB3CDX9", "PasswordAlfa", null, "0qLpWZIlpg2zlKSYcj0D" },
                    { "01J4G2Z4XTEZFMAQYCHCNB4WX0", "AlertBeforeAdministrativeAnalisisApprobation", null, "Señor funcionario" },
                    { "01J4G2Z4XTF0J78SZYRWJ93799", "EmailsNotificacionSubsanarDocumentos", null, "soporte.tesamerica@tesamerica.com.co" },
                    { "01J4G2Z4XTF1WSNQS3XRT2FNNP", "FirmaElectronicaAction", null, "urn:/#NewOperation" },
                    { "01J4G2Z4XTF3SXZHZBWW15ESXA", "EspTemp_AZDigital_TramiteRegistro", null, "rs" },
                    { "01J4G2Z4XTF62ABXYCM7ANZKGV", "MotivoRechazoCartera", null, "No cumplir con lo establecido en el numeral 2 del artículo 3 de la resolución 485 de 2024" },
                    { "01J4G2Z4XTF7F0H0Y6VZWG83MH", "CorreoDevolucionCT", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTF9FRPM9SJ31PSD8G", "IMT_AZDigital_TramiteRegistro", null, "RPTA_N" },
                    { "01J4G2Z4XTFAAAWANYYD3FSR0C", "ExplanationApplicationFileUpload", null, "Aliste los siguientes documentos: Formato básico de solicitud" },
                    { "01J4G2Z4XTFD7G48MY5TTPQE34", "CorreoRechazoMintic-Mintic", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTFJFAR3T3QCKP8NS2", "CorreoMinticSoporte", null, "soporte.tesamerica@tesamerica.com.co" },
                    { "01J4G2Z4XTFPGZ5AJ9HN21CQV1", "NombreMintic", null, "Ministerio TIC" },
                    { "01J4G2Z4XTFR364ZCWSSRBQ28S", "AZDigital_IdDirectorioRadicadoSatelital", null, "102235" },
                    { "01J4G2Z4XTFYCYSD9NTXZV83HK", "CustomerFrontContactInfo", null, "Para dudas o inquietudes respecto a la funcionalidad de esta aplicación" },
                    { "01J4G2Z4XTG3ECWRRNFG5JC2BF", "AZDigital_TramiteRadicado", null, "PQRSD" },
                    { "01J4G2Z4XTG82212JMZY9WS938", "UsuarioServicioAuraPortalNew", null, "mintic/bpmimpersonate" },
                    { "01J4G2Z4XTG8TZGJ9AP5CFCD3G", "ApiNotificaciones_Clave", null, "6ed4a3759c2234bcc9e144151b5d44bc" },
                    { "01J4G2Z4XTG8XQYZ0ZBXEZM0D1", "Fecha_Subsanacion_Coordinador_Satelital_Administrativo", null, "1" },
                    { "01J4G2Z4XTGDS9NECC3FD8EX5F", "TokenTMP_Email", null, "soporte.sge@mintic.gov.co" },
                    { "01J4G2Z4XTGDX9XV4ZJAV24MDF", "LogonMessageFront", null, "Señor funcionario" },
                    { "01J4G2Z4XTGF3R1058HH290R6Y", "Satelital_Portada_MINTIC", null, "Ministerio de Tecnologías de la Información y las Comunicaciones; solicitudessatelital@g.com" },
                    { "01J4G2Z4XTGKRHTWHMX6DWFCES", "Fecha_Subsanacion_Revisor_Satelital_Tecnico", null, "10" },
                    { "01J4G2Z4XTGMPB528DG0D98Z93", "NombreAne", null, "Agencia Nacional del Espectro" },
                    { "01J4G2Z4XTGNQ16SYFZZ90C5VQ", "CorreosAletaBloqueoGarantias", null, "andres.rodriguez@tesamerica.com.co,garantias@g.com" },
                    { "01J4G2Z4XTGQ4C19Q1CEMEXQ3V", "LegendCantFilegApplicationDetails", null, "Información faltante para radicar la solicitud" },
                    { "01J4G2Z4XTH5TN29G9SFF90YR0", "SubdirectorPSO", null, "gperdomo" },
                    { "01J4G2Z4XTH9J1N4G2X3KW4Z7V", "MailSmtpHost", null, "smtp.gmail.com" },
                    { "01J4G2Z4XTHAAT40S3FGD13SHK", "ExcelAutoliquidador", null, "Use el botón 'Cargar formato excel' si desea liquidar múltiples redes mediante un archivo .xls previamente diligenciado. El formato puede obtenerse haciendo clic en el botón 'Plantilla formato excel'" },
                    { "01J4G2Z4XTHBHDKEAFRJPYP076", "EmailMintic1", null, "soporte.tesamerica@tesamerica.com.co" },
                    { "01J4G2Z4XTHD28Q766CC2BFCGN", "CorreoDevolucionProceso", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTHG1PXV5NF6NSWT5E", "LogonMessageAdic", null, "o envíe un correo a minticresponde@mintic.gov.co" },
                    { "01J4G2Z4XTHG9ADAC148JDBGX5", "WfTipoAlfaInterno", null, "1" },
                    { "01J4G2Z4XTHGDY44WKBJQ72RT2", "AZDigital_Resoluciones_UsuarioFirmanteDir_EspTemp", null, "nalmeyda" },
                    { "01J4G2Z4XTHHW96WZARQ4GEAAM", "DocumentosSGE_URL", "URL de documentos del SGE", "https://cert-gestion-espectro.mintic.gov.co/DocSGE/DocSGE_Front" },
                    { "01J4G2Z4XTHKBC8TN5VAPB05GW", "AZDigital_TramiteRadicadoSatelital", null, "PQRSD" },
                    { "01J4G2Z4XTHPV7BE5P5DGNRVYM", "EspTemp_CorreoRechazoMINTIC_ANE", null, "Solicitudesdeespectro@g.com" },
                    { "01J4G2Z4XTHWHBT5NBSMZVYQ7F", "TextoDetalleAlfaRadicarArchivo", null, "Notificación de Radicación de Archivo  de la Solicitud: {0}" },
                    { "01J4G2Z4XTJ0430WVFHCHQD1BY", "FaxAne", null, "2436212" },
                    { "01J4G2Z4XTJ2X6K7JJ2CB7QGC6", "EmailAnalisisTecnico", null, "soporte.tesamerica@tesamerica.com.co" },
                    { "01J4G2Z4XTJ9516VDY5M2Y9T6Y", "AlertConfirmCreateObservation", null, "¿Está seguro que desea guardar el cambio?" },
                    { "01J4G2Z4XTJD3X88KCK6JT8FZ2", "FlashPlayer", "https://get.adobe.com/es/flashplayer/", "https://get.adobe.com/es/flashplayer/" },
                    { "01J4G2Z4XTJDQW0DE9M44831M2", "AZDigital_Resoluciones_UsuarioFirmanteVice_EspTemp", null, "svaldes" },
                    { "01J4G2Z4XTJEQ60CBKY528MTHP", "CorreosDocumentosRequeridosCoordinadorANE", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTJFJCA2RTXT3KYMKG", "CorreoRemitente", null, "soporte.tesamerica@tesamerica.com.co" },
                    { "01J4G2Z4XTJFTCTPFAVSX96008", "FirmaElectronicaAZAplicativo", null, "20201209-092929-982602-00332255" },
                    { "01J4G2Z4XTJFXGNYS8KZ60WJ34", "TechnicalInformationSummaryXmlMassivelyUploaded", null, "Información cargada masivamente a partir de archivo .xml" },
                    { "01J4G2Z4XTJFZRG5JFA6MGK4CY", "EstadosExpedienteRadicacionSerie", null, "eRES,eCT" },
                    { "01J4G2Z4XTJHY8Y7NFTRYHFKN1", "Satelital_FirmaElec_Director", null, "dreinales" },
                    { "01J4G2Z4XTJP071CWGBHA8K518", "TextoFirmaCertificadoEspectro", null, "Asesora del Despacho del Viceministerio de Transformación Digital encargada de las funciones del Subdirector para la Industria de Comunicaciones" },
                    { "01J4G2Z4XTJXB1KVC3B5KBP5GM", "CorreoTesamerica", null, "soporte.tesamerica@tesamerica.com.co" },
                    { "01J4G2Z4XTJXZ0VYEAMY06HTTM", "Garantia_Coordinador", null, "Coordinador del Grupo Interno de Trabajo Gestión de Garantías" },
                    { "01J4G2Z4XTK4XA54GQFF279X3N", "MainPatternAddress", null, "[a-z .;,:ñ¿?¡!(){}&%$_*+\\'@''/\\\\#|=º^¨~-]" },
                    { "01J4G2Z4XTK7NCNC8FNCYQ82MV", "AZDigital_IdDirectorioConsultaNOPSO", null, "24828" },
                    { "01J4G2Z4XTKAXT3C0NETQ76J3M", "EntornoPruebas", null, "1" },
                    { "01J4G2Z4XTKB0DRXJ8JMJNESHQ", "MensajeCrearExpediente", null, "<div class='nombre_campo'><p style='margin:20px; text-align:justify;'>Señor usuario:</p><br/><p style='margin:20px; text-align:justify;'>El usuario acepta que a través del registro en el sitio web" },
                    { "01J4G2Z4XTKCEQ74XGD8JXRNWQ", "NumeroArchivosRadicacion", null, "2" },
                    { "01J4G2Z4XTKJ0FP6RD868XHWZ5", "EstadosExpedienteMuerto", null, "eX0,eX1,eX1B,eX2B,eX3,eX4,eX4B" },
                    { "01J4G2Z4XTKKCHEM9NQAVSK7AB", "ExplanationApplicationFileList", null, "A continuación se listan los archivos adjuntos a la solicitud seleccionada." },
                    { "01J4G2Z4XTKMMYX4R8BFXPVZGF", "FirmaElectronicaAZGrupo", null, "20211007-161726-6bbb98-36629518" },
                    { "01J4G2Z4XTKNSM60N1DR9WR74F", "EspTemp_CorreoAprobacionResolucion", null, "solicitudesane@g.com,kballen@g.com,crojas@g.com,ligomez@g.com" },
                    { "01J4G2Z4XTKZ75YK36YCX44ZMC", "EstadosExpedienteNoUsadosPSO", null, "eCT,eRES,eVEN,eX0,eX1,eX1B,eX2B,eX3,eX4,eX4B" },
                    { "01J4G2Z4XTM2ECCX54PPCT504B", "TokenTMP_Rol", null, "128" },
                    { "01J4G2Z4XTM3T74FNDT0KD6YWM", "CorreosMarcacionLocalidad", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTM458SMPVV5NAK48W", "ExplanationSimulacionSpectrumE", null, "Ingrese a esta opción si desea simular algún enlace usando el Sistema de Simulación en Línea." },
                    { "01J4G2Z4XTM4R93CWK8F2AMRF9", "EstadosExpedienteSincronizacion", null, "eAUT" },
                    { "01J4G2Z4XTM9WBCDQ80YPPA2TN", "DependenciaAlfa", null, "sage001" },
                    { "01J4G2Z4XTMAS57GEGJNX8JBTQ", "ApiNotificaciones_PlantillaEmail", null, "EmailNotificacion.html" },
                    { "01J4G2Z4XTMBDEEN78PVKKRTXD", "TextoRefRegistroAnalisisAdministrativo", null, "Traslado para Análisis Técnico de la Solicitud con radicado No. {0} del {1}." },
                    { "01J4G2Z4XTMD2YKG596BZXBKRH", "NaturalezaAlfaSolicitud", null, "100" },
                    { "01J4G2Z4XTMDFP9965PX6PCS35", "LegendFilingApplicationDetails", null, "Radicación de la solicitud" },
                    { "01J4G2Z4XTMES54RMY046X2T3M", "AdvertenciaFlash", null, "Para el correcto funcionamiento de la herramienta es necesario actualizar Flash Player" },
                    { "01J4G2Z4XTMM2MXG20VZC7ZND5", "TermsAndConitions", null, "Términos y condiciones: como usuario de la aplicación" },
                    { "01J4G2Z4XTMPZH79CTMSCXJ2WF", "IMT_Temp_File", null, "C:\\SAGE\\CargueIMT\\IMT_Back\\tempdatafile" },
                    { "01J4G2Z4XTMRD04YE01Y1FZTZ3", "AZDigital_IdDirectorioRadicadoPSO", null, "6369" },
                    { "01J4G2Z4XTMS82EXCECQK9BDHZ", "EspTemp_AZDigital_IdDirectorio", null, "6369" },
                    { "01J4G2Z4XTN41M400PS71MMN0P", "ServicioAuraQuantic", "Link de consumo para servicio AuraQuantic", "https://uatbpm-integraciones.mintic.gov.co:8001/ServiciosRUTIC/api/Rutic/ConsultarDatosAdministrativos" },
                    { "01J4G2Z4XTN5QB99Z1QT0D776F", "MailRevisorModuloResolucionesSinGarantia", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTN8NXB2MEH37KE855", "Temp_File_Satelital_New", null, "C:\\SAGE\\Satelital\\Satelital_Back\\tempdatafile" },
                    { "01J4G2Z4XTN8P1CB41VG26KEBJ", "NitMintic", null, "89999953-1" },
                    { "01J4G2Z4XTNBQFE3X7W4FS92JP", "CorreoCoordinacion_GGERE", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTNDNB9B56RE3140VJ", "MensajeInfoEmergenciaSeguridad", null, "Las solicitudes que se realizan en esta sección se encuentran exceptuadas del procedimiento de selección objetiva" },
                    { "01J4G2Z4XTNGH9DMBS2HN7XN1J", "NombreArchivoAlfaRadicarArchivo", null, "Radicación_Archivo_Solicitud_{0}_{1:ddMMyyHHmmss}.rtf" },
                    { "01J4G2Z4XTNRP979AE0QJRSFK9", "AZDigital_Resoluciones_TipoActo", null, "R" },
                    { "01J4G2Z4XTNRZ9MGAEJAT9KJNP", "MensajeInfoPSOP1", null, "Las solicitudes que se realizan en esta sección deben ser tramitadas bajo un Proceso de Selección Objetiva- PSO" },
                    { "01J4G2Z4XTNWEWN4SK3J0X8VA9", "LegendSpectrumE", null, "Sistema de Simulación" },
                    { "01J4G2Z4XTP5KAW47BKQPZQE79", "CorreoResumenTecnico", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTP79F9T467647RARH", "ExplanationApplicationDetailsRadicar", null, "Señor usuario" },
                    { "01J4G2Z4XTP809XN824VCW20ZR", "CorreosDocumentosRequeridosCoordinador", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTP8J0RFYNS7065KW6", "Garantia_Director", null, "Director de Industria de Comunicaciones" },
                    { "01J4G2Z4XTP9HYZ5GM9TGK0MG8", "EstadosExpedienteNoUsadosFueraPSO", null, "eVEN,eX0,eX1,eX1B,eX2B,eX3,eX4,eX4B" },
                    { "01J4G2Z4XTPE85FM668HWY0BPS", "NitAne", null, "9003342653" },
                    { "01J4G2Z4XTPGV856GZY4SJPQF6", "CorreoAprobacionANE-MINTIC_Satelital", null, "solicitudessatelital@g.com,Paola@g.com" },
                    { "01J4G2Z4XTPHNPRSMGW7KSAKRM", "SupportEmail", "(soporte.sge@mintic.gov.co)", "mailto:soporte.sge@mintic.gov.co" },
                    { "01J4G2Z4XTPKVJ5P88818NDTSV", "EspTemp_ExtensionArchivoPatronRadiacion", null, ".bmp,.gif,.heif,.heic,.jpg,.jpeg,.png,.psd,.svg,.tif,.tiff,.doc,.docx,.md,.odt,.pdf,.ppt,.pptx,.rtf,.txt,.xls,.xlsx,.7z,.rar,.zip" },
                    { "01J4G2Z4XTPNKAQR9XBM468FN6", "ExplanationApplicationDetailsEditarInfoTecnicaFuncionario", null, "Señor funcionario" },
                    { "01J4G2Z4XTPQA75MXBDFW31WVQ", "TelefonoAne1", null, "3442299" },
                    { "01J4G2Z4XTPWE19MSJ382J6Y55", "MensajeAdvertenciaRTICDiferenciasPSO", null, "Señor usuario" },
                    { "01J4G2Z4XTPZZEA46CA6M9895K", "MotivoRechazoGarantias", null, "No cumplir con lo establecido en el numeral 3 del artículo 3 de la resolución 485 de 2024" },
                    { "01J4G2Z4XTQ3TESE4NYZKMXENB", "MensajeBloqueoCartera", null, "Señor usuario" },
                    { "01J4G2Z4XTQ88NRK0C34JPEWKG", "MailUsername", null, "Soporte Tesamerica" },
                    { "01J4G2Z4XTQ91ZAGYK7370PXR6", "RolesPermisoModuloResoluciones", null, "1,2,3,4,5,6,7,10,21,22,30,57,59,60,61,62,72,73,74,75,76,77,78,79,98,99,100,101,107,108" },
                    { "01J4G2Z4XTQBT6XVTYGM25NXMX", "ApproveAdministrativeAnalisisWfTipo", null, "0" },
                    { "01J4G2Z4XTQDNY0GQR2ZJJEWGJ", "CorreoDesistimientoOperador", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTQQBKJ9CSG47EZR1N", "ExplanationEquipmentList", null, "Para el caso de monitores de modulación y monitor de frecuencia y la línea de transmisión en las redes de radiodifusión sonora (AM" },
                    { "01J4G2Z4XTQQNJF201VXNW26FF", "ExplanationApplicationDetailsRadicarFuncionario", null, "Señor funcionario" },
                    { "01J4G2Z4XTQW51BGNM6K83GX4K", "AlertBeforeRadicationError", null, "Señor operador" },
                    { "01J4G2Z4XTQWGW17W21TYFM8MB", "CuadroNacionalAtribucionesFrecuenciaLink", null, "http://www.mintic.gov.co/images/documentos/espectro_radioelectrico/cuadro_nacional/cuadro_nacional_atribucion_bandas_de_frecuencias_2010.pdf" },
                    { "01J4G2Z4XTR00F02MNW456NFXN", "AZDigital_TramiteRegistro", null, "rs" },
                    { "01J4G2Z4XTR2XYVM8NV8GB8QZS", "CorreoRadicadoANEPSO", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTR7E9ZR38MRPDM32S", "IMT_CorreoRadicarMinticyANE", null, "Solicitudesdeespectro@g.com,juan.benavides@tesamerica.com.co,dircom@g.com" },
                    { "01J4G2Z4XTR96D982HW27BKYRJ", "ApproveTechnicalAnalisisCdDestino", null, "311" },
                    { "01J4G2Z4XTREP2AX9ZRMRB0N2B", "MainPatternRazonSocial", null, "[^a-z]" },
                    { "01J4G2Z4XTRHBDWEZ3Q0NV1P03", "ServicioSGE-RUESLocal", "Link de consumo para el servicio SGE-RUES", "http://192.168.0.10:8749/api/rues/consultaRUES" },
                    { "01J4G2Z4XTRJ0QB63BCF713C7X", "SupportEmail_Prueba", "rsandoval@mintic.gov.co", "mailto:rsandoval@mintic.gov.co" },
                    { "01J4G2Z4XTRKJ0FAAFDWDR4DTD", "FechaInicioMantenimiento", null, "11/10/2023 20:00:00.000" },
                    { "01J4G2Z4XTRT6Z3PDZXAQ85GB3", "ExplanationTechnicalInformationEdit", null, "Información general y creación de antenas" },
                    { "01J4G2Z4XTS077V06CZCE4X326", "CustomerFrontProcessInfo", null, "El Sistema para la Gestión del Espectro Radioeléctrico “SGE”" },
                    { "01J4G2Z4XTS5WGFHH4W9BR8CX0", "ExplanationApplicationDetailsAnexarArchivosFuncionario", null, "Señor funcionario" },
                    { "01J4G2Z4XTS7X0DRNJTYG8KC3N", "AZDigital_TramiteRegistroSatelital", null, "RPTA_S" },
                    { "01J4G2Z4XTSC1VGB2FKZXA7E47", "ExplanationAdicionarObservacion", null, "Por favor ingrese la razón por la cual realizó este cambio" },
                    { "01J4G2Z4XTSE43TBWPH8R5MWQS", "CorreoCertificadoCanalesEmailCertificado", null, "1" },
                    { "01J4G2Z4XTSJYP2R3204HJVYFF", "ExplanationApplicationDetailsAnexarArchivos", null, "Señor usuario" },
                    { "01J4G2Z4XTSP3BTANF8PK9YZ5P", "Temp_File_EspectroTemporal", null, "C:\\SAGE\\EspectroTemporal\\EspectroTemp_Back\\tempdatafile" },
                    { "01J4G2Z4XTSQC95QK93CWTFBXH", "TokenTMP_SecretKey", null, "F4209FA7-FAF6-4BF0-8A5E-783BE439DF9E" },
                    { "01J4G2Z4XTSRYT63MEYWT9YA9A", "AZDigital_Resoluciones_UsuarioFirmante_Satelital", null, "nalmeyda" },
                    { "01J4G2Z4XTSSPCPYNEKCAS24ZV", "ServicioSGE-RUES", "Link de consumo para el servicio SGE-RUES", "http://salicaria:8749/api/rues/consultaRUES" },
                    { "01J4G2Z4XTSV9X8SD2GK2Q7MR5", "FirmaElectronicaAZURL", "Link consumo para el servicio de firma electrónica (AZSign)", "https://azsign.analitica.com.co/WebServices/SOAP/" },
                    { "01J4G2Z4XTSX4DGBW2XVC4SSXJ", "ExplanationDuplexerCreation", null, "Formulario de creación de duplexor" },
                    { "01J4G2Z4XTSY7BPXGGR33WYB5A", "MensajeInfoNOPSO", null, "Las solicitudes que se realizan en esta sección corresponden a las que pueden ser tramitadas fuera de un Proceso de Selección Objetiva- PSO" },
                    { "01J4G2Z4XTT1ZDQ6VDJ5J024Q2", "IMT_AZDigital_Dependencia", null, "2.2" },
                    { "01J4G2Z4XTT632CDNQW41Z9ABW", "EsPrueba", null, "true" },
                    { "01J4G2Z4XTT8C6MJMGMNZ7TF66", "CorreoCertificadoCanalesMerge", null, "0" },
                    { "01J4G2Z4XTT8SVY2EZ5EYKG65W", "EspTemp_CorreoCopiaANE-MINTIC", null, "solicitudesane@g.com" },
                    { "01J4G2Z4XTTC16DT9TDAY8PEY9", "ApiNotificaciones_URIPlantilla", null, "TesAmerica.docx" },
                    { "01J4G2Z4XTTD0GETX06KAYCAQN", "FirmaElectronicaAZContraseña", null, "b1a8262799b1746913b4476ab1b17238" },
                    { "01J4G2Z4XTTD9RWCA8NGEWGM2S", "CityCodeMintic", null, "11001" },
                    { "01J4G2Z4XTTDYHKQZMH8SC462B", "ApproveTechnicalAnalisisWfTipo", null, "0" },
                    { "01J4G2Z4XTTH0C2ZKRVT36W4A3", "AZDigital_Resoluciones_UsuarioFirmante_EyS", null, "svaldes" },
                    { "01J4G2Z4XTTHBRNZVQWMHGSWQM", "FirmaElectronicaUrl", null, "https://azsign.analitica.com.co/WebServices/SOAP/" },
                    { "01J4G2Z4XTTJBYMPTZ5PJE6717", "ExplanationEquipmentCreation", null, "Formulario de creación de equipo" },
                    { "01J4G2Z4XTTJY3ZJZ67CVANMX3", "EspTemp_AZDigital_Sitio", null, "Prue" },
                    { "01J4G2Z4XTTKXXRWS26Q3NW8CY", "EspTemp_CorreoCopiaMINTIC-ANE", null, "Solicitudesdeespectro@g.com" },
                    { "01J4G2Z4XTTMVVQKT2VDNWS4RY", "CorreosDesmarcacionLocalidad", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTTMX7VGDX08B8NKET", "MailSmtpPassword", null, "Tesamerica123*" },
                    { "01J4G2Z4XTTPJZ4SRC891E4Y7F", "CorreoCertificadoCanalesPlantillaEmail", null, "EmailNotificacion.html" },
                    { "01J4G2Z4XTTR96MRFMWAE0G439", "EspTemp_Fecha_Subsanacion_Tec", null, "1" },
                    { "01J4G2Z4XTTV1W4HGTH87SPJZB", "SystemDescription", null, "El Sistema para la Gestión del Espectro Radioeléctrico “SGE” permite a los titulares de permiso para el uso del espectro tramitar ante el Ministerio de Tecnologías de la Información y las Comunicaciones" },
                    { "01J4G2Z4XTTVY9TNWZ721NBR7Y", "CorreoCertificadoRemitenteDireccion", null, "Casa 1" },
                    { "01J4G2Z4XTTZRXNZV0Y573W8X2", "GraficaNacionalAtribucionesFrecuenciaLink", null, "http://www.mintic.gov.co/images/documentos/espectro_radioelectrico/cuadro_nacional/grafico_cuadro_nacional.pdf" },
                    { "01J4G2Z4XTV3B0BY7VC1DHQ4TQ", "FilesSummaryFilesCount", null, "Número de archivos adjuntos:" },
                    { "01J4G2Z4XTV5ACB1DN2KXKFVA1", "TokenTMP_TypeIdent", null, "NIT" },
                    { "01J4G2Z4XTVDRHBNJCWM6R1B3B", "CorreoRechazoMINTIC_ANE_Satelital", null, "Solicitudesdeespectro@g.com" },
                    { "01J4G2Z4XTVGXKC0B1XM7FJF94", "MensajePrevioMantenimiento", null, "El Ministerio de Tecnologías de la Información/Fondo Único de TIC informa que el próximo <b>{0} hasta las {1}</b> realizara mantenimiento al aplicativo. <b>Durante este mantenimiento los servicios no estarán disponibles.</b> Agradecemos su comprensión no ingresando a la aplicación en esta franja de tiempo." },
                    { "01J4G2Z4XTVJZB93DVA1WF9YP6", "EspTemp_VersionFormatoAnexo", null, "1,1" },
                    { "01J4G2Z4XTVVSN09DGVEXMSQCA", "Resolucion", null, "485 de 2024" },
                    { "01J4G2Z4XTVY1AKJ26B4PCMKQ7", "AlertBeforeFileDeleting", null, "¿Está seguro que desea eliminar este archivo?" },
                    { "01J4G2Z4XTW0850CY8S631SFTC", "EspTemp_CorreoAprobacionMINTIC-ANE", null, "Solicitudesdeespectro@g.com,ruben.zuleta@tesamerica.com.co" },
                    { "01J4G2Z4XTW2T84ATKR3S4VV61", "SerieDocumentalAlfa", null, "100" },
                    { "01J4G2Z4XTW46HYPX0RS9EYSGR", "PaginaMinisterio", null, "http://www.mintic.gov.co/" },
                    { "01J4G2Z4XTW54FTFYE7SAAF9NX", "FirmaElectronicaAZEstado", null, "1-P" },
                    { "01J4G2Z4XTW649VQP3JBDQHYH3", "ExplanationTechnicalInformationIndex", null, "Visualización de la información técnica de la solicitud" },
                    { "01J4G2Z4XTW6G8J010VP8DCZ6D", "ApiNotificaciones_Action", null, "urn:/#NewOperation" },
                    { "01J4G2Z4XTWA39JEW1K0GW2258", "EspTemp_PortadaANE", null, "Agencia Nacional del Espectro;Solicitudesdeespectro@g.com" },
                    { "01J4G2Z4XTWK8BBVJ3S24H9F49", "CorreosAletaBloqueoRUTIC", null, "andres.rodriguez@tesamerica.com.co,rutic@g.com" },
                    { "01J4G2Z4XTWN5KK4Z8SCWEXSM8", "EspTemp_CorreoRadicarMintic", null, "solicitudesane@g.com" },
                    { "01J4G2Z4XTWPMWGZNR0K25QWM4", "TelefonoMintic1", null, "3443460" },
                    { "01J4G2Z4XTWVAZA1AQV5RACRBD", "EstadosRedesVAC", null, "rAUT,rRES,rPRN,rPRE,rTT" },
                    { "01J4G2Z4XTWVEQ20D7ZDXDJ82C", "CodigoDestinoAne", null, "pru001" },
                    { "01J4G2Z4XTWYR0DA47XS902TC5", "ApiNotificaciones_TipoMime", null, "application/pdf" },
                    { "01J4G2Z4XTX0ASGZSWAQC48A61", "ExplanationApplicationCreationPortfolio", null, "Debe hacer una solicitud por expediente y la documentación debe corresponder al expediente que está tramitando." },
                    { "01J4G2Z4XTX7DBW30CGJ1DPZZH", "CorreosSubsanacionOperadorCopiaOculta", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTXBXAVBPXQSS56PV7", "DireccionAne", null, "Calle 93B # 16-47" },
                    { "01J4G2Z4XTXCWGTA7FJA08HVH9", "FirmaElectronicaAZTipoFirma", null, "E" },
                    { "01J4G2Z4XTXM95YF8DT6K6A1TN", "VersionFormatosAnexos_Satelital", null, "V1.4" },
                    { "01J4G2Z4XTXMYRHWTP0QH5PX97", "ExplanationApplicationClosing", null, "Las solicitudes en cierre se encuentran en proceso de generación de la resolución" },
                    { "01J4G2Z4XTXQWYMWHRP3SW30ZH", "ApproveAdministrativeAnalisisCdDestino", null, "311" },
                    { "01J4G2Z4XTXR7D466H3S0917QX", "ExplanationApplicationMessageListSummaryNoNotes", null, "No se encontraron anotaciones." },
                    { "01J4G2Z4XTXS1K8N69BZFVJSHG", "EstadosExpedienteRadicacionParalelo", null, "eAUT,eSOL" },
                    { "01J4G2Z4XTXTE1QCFWEKNM083W", "CorreosAlertaCesionRedes", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTXYS0T7V2C98FS24Y", "CorreoAprobacionMinTIC", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTY322XBXBQFSCGVAN", "UbicacionDocumentosSGE", null, "C:\\SAGE\\DocumentosSGE\\" },
                    { "01J4G2Z4XTY65WGV92KJF5SMG3", "LogonMessage", null, "Escriba su usuario y contraseña de Registro TIC" },
                    { "01J4G2Z4XTY7FY5SPVC9HS20B8", "RegistroTicUrl", "Registro de TIC", "http://www.mintic.gov.co/portal/604/w3-article-6398.html" },
                    { "01J4G2Z4XTYAJ9SD6BY2Q8HTX3", "CorreosSubasanacionANE", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTYEE02WWPSJ26TXZ5", "EmailMintic2", null, "No disponible" },
                    { "01J4G2Z4XTYM8C12PXSYV752G9", "ExplanationApplicationDetailsEditarInfoTecnica", null, "Señor usuario" },
                    { "01J4G2Z4XTYNQKZBYG2Z0DRK8J", "TextoNotificacionSigpol", null, "Señor usuario una de sus garantías presenta una novedad" },
                    { "01J4G2Z4XTYQFAEPF893DBJJAQ", "Clases_Expedientes_Industria", null, "97,95,20" },
                    { "01J4G2Z4XTYSEEAP3HH7933191", "TokenTMP_User", null, "Sistema de Gestión del Espectro" },
                    { "01J4G2Z4XTYT08PY9082X2KKBW", "BDU_Clase", null, "92" },
                    { "01J4G2Z4XTYV3YH38TDEDPWQKT", "FirmaElectronicaRefWebHook", null, "AZDigital: (5)" },
                    { "01J4G2Z4XTYVKZGD9DFZ31PV4K", "CorreosRechazoSolicitudANE", null, "andres.rodriguez@tesamerica.com.co" },
                    { "01J4G2Z4XTYW4GWAEA6N10J5PZ", "SolFisicaDiasAdicionalFechaVenc", null, "60" },
                    { "01J4G2Z4XTYWE48H2GFNG828TG", "AdvertenciaNavegador", null, "Te recomendamos usar los siguientes navegadores para que tu experiencia con el SGE sea óptima: <img style='width:16px;vertical-align:text-bottom;' src='/content/images/icons/chrome24.png' alt='Icono del navegador Google Chrome'>Google Chrome V.49 y <img style='width:16px;vertical-align:text-bottom;' src='/content/images/icons/firefox24.png' alt='Icono del navegador Mozilla'>Mozilla Firefox V.42 o versiones superiores." },
                    { "01J4G2Z4XTYYF8BWCZAKMZ5HC1", "EstadosExpedienteDatosContacto", null, "eREG" },
                    { "01J4G2Z4XTYZTB1MHJ800PWEZC", "CorreoCertificadoDocumentosMerge", null, "0" },
                    { "01J4G2Z4XTZ4E4JA63ZXTRM18R", "PointToPointAndPointToMultipointExplanation", null, "Si por algún motivo" },
                    { "01J4G2Z4XTZ6N141315AS7TCGZ", "Satelital_CorreoFinResolucionMINTIC", null, "ebernate@g.com,kballen@g.com,carengifo@g.com,crojas@g.com,aruiz@g.com,nmendez@g.com" },
                    { "01J4G2Z4XTZDN70ANS7Q4H9YAM", "MetodoEnvioAlfa", null, "TL" },
                    { "01J4G2Z4XTZGSHMRJNY7W4GWA6", "MensajeAdvertenciaGarantias", null, "Señor usuario" },
                    { "01J4G2Z4XTZR6CFYZ3521S8JH1", "ExplanationPortfolioGrid", null, "Listado de expedientes. Utilice los íconos frente a cada expediente para observar los detalles o editar. Si no encuentra el número de expediente deseado" },
                    { "01J4G2Z4XTZRC4TV79MQ6FWD38", "PasswordRUES", null, "k272ki8bLnLpFK7aUuUEzw==" },
                    { "01J4G2Z4XTZS8TK1TWP7CXX895", "AZDigital_SitioSatelital", null, "TL" },
                    { "01J4G2Z4XTZSCJVYP79TR4FQ81", "CorreoRechazoANE-MINTIC_Satelital", null, "solicitudessatelital@g.com,Paola@g.com" },
                    { "01J4G2Z4XTZSX7S2GRXZCQ5GC6", "AZDigital_IdDirectorioRadicadoNOPSO", null, "6369" },
                    { "01J4G2Z4XTZXQ7EE8BJ652EXTH", "ExplanationApplicationSolve", null, "Consulte el histórico de las solicitudes finalizadas" },
                    { "01J4G2Z4XTZYEWWKDHN1EFR4VX", "NombreArchivoAlfaAnalisisTecnico", null, "Aprobacion_Tecnica_Solicitud_{0}_{1:ddMMyyHHmmss}.rtf" }
                });

            migrationBuilder.CreateIndex(
                name: "IX_dynamic_texts_Code",
                table: "dynamic_texts",
                column: "Code",
                unique: true);
        }

        /// <inheritdoc />
        protected override void Down(MigrationBuilder migrationBuilder)
        {
            migrationBuilder.DropTable(
                name: "dynamic_texts");
        }
    }
}
