using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

using SGE.Domain.DynamicTextAggregate;
using SGE.Domain.DynamicTextAggregate.ValueObjects;
using SGE.Domain.TermAggregate.ValueObjects;

namespace SGE.Infrastructure.DynamicTexts.Persistence;

public class DynamicTextConfigurations : IEntityTypeConfiguration<DynamicText>
{
    public void Configure(EntityTypeBuilder<DynamicText> builder)
    {
       builder.ToTable("DynamicTexts");

       builder.HasKey(x => x.Id);

       builder.Property(x => x.Id)
           .ValueGeneratedNever()
           .HasConversion(id => id.Value, value => DynamicTextId.Create(value));

       builder.HasIndex(x => x.Code).IsUnique();
       builder.Property(x => x.Description).IsRequired(false);

       ApplyTextSeeder(builder);
       ApplyLinksSeeder(builder);
    }

    private void ApplyTextSeeder(EntityTypeBuilder<DynamicText> builder)
    {
       builder.HasData(
                DynamicText.Create(@"AdvertenciaFlash", @"Para el correcto funcionamiento de la herramienta es necesario actualizar Flash Player", null),
                DynamicText.Create(@"AdvertenciaNavegador", @"Te recomendamos usar los siguientes navegadores para que tu experiencia con el SGE sea óptima: <img style='width:16px;vertical-align:text-bottom;' src='/content/images/icons/chrome24.png' alt='Icono del navegador Google Chrome'>Google Chrome V.49 y <img style='width:16px;vertical-align:text-bottom;' src='/content/images/icons/firefox24.png' alt='Icono del navegador Mozilla'>Mozilla Firefox V.42 o versiones superiores.", null),
                DynamicText.Create(@"AlertBeforeAdministrativeAnalisisApprobation", @"Señor funcionario", null),
                DynamicText.Create(@"AlertBeforeClosingApproval", @"Señor funcionario", null),
                DynamicText.Create(@"AlertBeforeDeleting", @"Señor usuario", null),
                DynamicText.Create(@"AlertBeforeFileDeleting", @"¿Está seguro que desea eliminar este archivo?", null),
                DynamicText.Create(@"AlertBeforeRadication", @"Señor usuario: tenga en cuenta que una vez radicada la solicitud", null),
                DynamicText.Create(@"AlertBeforeRadicationAdicional", @"Sr. Usuario", null),
                DynamicText.Create(@"AlertBeforeRadicationError", @"Señor operador", null),
                DynamicText.Create(@"AlertBeforeTechnicalAnalisisApprobation", @"Señor funcionario", null),
                DynamicText.Create(@"AlertConfirmCreateObservation", @"¿Está seguro que desea guardar el cambio?", null),
                DynamicText.Create(@"ApiNotificaciones_Action", @"urn:/#NewOperation", null),
                DynamicText.Create(@"ApiNotificaciones_Aplicacion", @"TesAmerica", null),
                DynamicText.Create(@"ApiNotificaciones_Clave", @"6ed4a3759c2234bcc9e144151b5d44bc", null),
                DynamicText.Create(@"ApiNotificaciones_PlantillaEmail", @"EmailNotificacion.html", null),
                DynamicText.Create(@"ApiNotificaciones_TipoMime", @"application/pdf", null),
                DynamicText.Create(@"ApiNotificaciones_URIPlantilla", @"TesAmerica.docx", null),
                DynamicText.Create(@"ApiNotificaciones_Url", @"https://integratic.mintic.gov.co/Notificaciones/Webservices/SOAP/", null),
                DynamicText.Create(@"ApiNotificaciones_Usuario", @"20231218-163125-18a4c0-17460376", null),
                DynamicText.Create(@"ApproveAdministrativeAnalisisCdDestino", @"311", null),
                DynamicText.Create(@"ApproveAdministrativeAnalisisNaturaleza", @"770", null),
                DynamicText.Create(@"ApproveAdministrativeAnalisisSerieDocumental", @"Serie Documental", null),
                DynamicText.Create(@"ApproveAdministrativeAnalisisWfTipo", @"0", null),
                DynamicText.Create(@"ApproveTechnicalAnalisisCdDestino", @"311", null),
                DynamicText.Create(@"ApproveTechnicalAnalisisNaturaleza", @"770", null),
                DynamicText.Create(@"ApproveTechnicalAnalisisSerieDocumental", @"Serie Documental", null),
                DynamicText.Create(@"ApproveTechnicalAnalisisWfTipo", @"0", null),
                DynamicText.Create(@"AZDigital_Dependencia", @"Pru", null),
                DynamicText.Create(@"AZDigital_DependenciaSatelital", @"2.2.0.1", null),
                DynamicText.Create(@"AZDigital_IdDirectorioConsultaNOPSO", @"24828", null),
                DynamicText.Create(@"AZDigital_IdDirectorioConsultaPSO", @"24828", null),
                DynamicText.Create(@"AZDigital_IdDirectorioRadicadoNOPSO", @"6369", null),
                DynamicText.Create(@"AZDigital_IdDirectorioRadicadoPSO", @"6369", null),
                DynamicText.Create(@"AZDigital_IdDirectorioRadicadoSatelital", @"102235", null),
                DynamicText.Create(@"AZDigital_Resoluciones_Dependencia", @"100", null),
                DynamicText.Create(@"AZDigital_Resoluciones_ProcedeRecurso", @"Rep10", null),
                DynamicText.Create(@"AZDigital_Resoluciones_TipoActo", @"R", null),
                DynamicText.Create(@"AZDigital_Resoluciones_TipoNotificacionCorreo", @"CE", null),
                DynamicText.Create(@"AZDigital_Resoluciones_TipoNotificacionFisico", @"P", null),
                DynamicText.Create(@"AZDigital_Resoluciones_UsuarioFirmante", @"nalmeyda", null),
                DynamicText.Create(@"AZDigital_Resoluciones_UsuarioFirmante_EyS", @"svaldes", null),
                DynamicText.Create(@"AZDigital_Resoluciones_UsuarioFirmante_Satelital", @"nalmeyda", null),
                DynamicText.Create(@"AZDigital_Resoluciones_UsuarioFirmanteDir_EspTemp", @"nalmeyda", null),
                DynamicText.Create(@"AZDigital_Resoluciones_UsuarioFirmanteVice_EspTemp", @"svaldes", null),
                DynamicText.Create(@"AZDigital_Sitio", @"Prue", null),
                DynamicText.Create(@"AZDigital_SitioSatelital", @"TL", null),
                DynamicText.Create(@"AZDigital_TramiteRadicado", @"PQRSD", null),
                DynamicText.Create(@"AZDigital_TramiteRadicadoSatelital", @"PQRSD", null),
                DynamicText.Create(@"AZDigital_TramiteRegistro", @"rs", null),
                DynamicText.Create(@"AZDigital_TramiteRegistroSatelital", @"RPTA_S", null),
                DynamicText.Create(@"BDU_Clase", @"92", null),
                DynamicText.Create(@"CausaRechazoNOSubsanar", @"No cumplir con lo establecido en el numeral 1", null),
                DynamicText.Create(@"CertificacionCarteraTextoFirma", @"Coordinadora GIT de Cartera", null),
                DynamicText.Create(@"CertificacionGarantiasTextoFirma", @"Coordinador GIT de Gestión de Garantías", null),
                DynamicText.Create(@"CityCodeAne", @"11001", null),
                DynamicText.Create(@"CityCodeMintic", @"11001", null),
                DynamicText.Create(@"Clases_Expedientes_Industria", @"97,95,20", null),
                DynamicText.Create(@"Clases_Expedientes_Satelital", @"92", null),
                DynamicText.Create(@"ClasesExpedienteRTIC", @"96,81,83,84,86,87,88,89", null),
                DynamicText.Create(@"CodigoDestinoAne", @"pru001", null),
                DynamicText.Create(@"CodigoDestinoMintic", @"pru001", null),
                DynamicText.Create(@"Columna_Potencia_BB", @"R", null),
                DynamicText.Create(@"CoordinadorPSO", @"ogarzon", null),
                DynamicText.Create(@"CorreoAprobacionANE-MINTIC_Satelital", @"solicitudessatelital@g.com,Paola@g.com", null),
                DynamicText.Create(@"CorreoAprobacionMinTIC", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoAprobacionMINTIC-ANE_Satelital", @"Solicitudesdeespectro@g.com", null),
                DynamicText.Create(@"CorreoAprobacionResolucionRevisor5", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoCertificadoAplicacion", @"TesAmerica", null),
                DynamicText.Create(@"CorreoCertificadoCanalesAsunto", @"Prueba Email Servicio Notificaciones", null),
                DynamicText.Create(@"CorreoCertificadoCanalesEmailCertificado", @"1", null),
                DynamicText.Create(@"CorreoCertificadoCanalesMensaje", @"Mensaje del Email Pruebas", null),
                DynamicText.Create(@"CorreoCertificadoCanalesMerge", @"0", null),
                DynamicText.Create(@"CorreoCertificadoCanalesPlantillaEmail", @"EmailNotificacion.html", null),
                DynamicText.Create(@"CorreoCertificadoContraseña", @"2eca78d9b47f82705c9bbc5efe71cd95", null),
                DynamicText.Create(@"CorreoCertificadoDocumentosCodificacion", @"Base64", null),
                DynamicText.Create(@"CorreoCertificadoDocumentosMerge", @"0", null),
                DynamicText.Create(@"CorreoCertificadoDocumentosTipoMime", @"application/pdf", null),
                DynamicText.Create(@"CorreoCertificadoRemitenteCargo", @"Representante Legal", null),
                DynamicText.Create(@"CorreoCertificadoRemitenteDireccion", @"Casa 1", null),
                DynamicText.Create(@"CorreoCertificadoRemitenteEmail", @"silvia.mesino@analitica.com.co", null),
                DynamicText.Create(@"CorreoCertificadoRemitenteNombre", @"Andres Rodriguez", null),
                DynamicText.Create(@"CorreoCertificadoUsuario", @"20230922-132449-805237-73089455", null),
                DynamicText.Create(@"CorreoCoordinacion_GGCCG", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoCoordinacion_GGERE", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoCopiaANE", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoCopiaANE-MINTIC_Satelital", @"Solicitudesdeespectro@g.com", null),
                DynamicText.Create(@"CorreoCopiaMINTIC-ANE_Satelital", @"solicitudessatelital@g.com,Paola@g.com", null),
                DynamicText.Create(@"CorreoDesistimientoOperador", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoDevolucionCT", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoDevolucionProceso", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoEnvioAdjuntoRadicarSatelitalANE", @"Solicitudesdeespectro@g.com,ruben.zuleta@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoEnvioANE-Mintic", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoEnvioANE-MinticNOPSO", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoEnvioRadicarSatelitalANE-Mintic", @"solicitudessatelital@g.com,Paola@g.com", null),
                DynamicText.Create(@"CorreoInformeEvaluacion", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoMinticSoporte", @"soporte.tesamerica@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoRadicadoANEPSO", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoRechazoANE-MINTIC_Satelital", @"solicitudessatelital@g.com,Paola@g.com", null),
                DynamicText.Create(@"CorreoRechazoMINTIC_ANE_Satelital", @"Solicitudesdeespectro@g.com", null),
                DynamicText.Create(@"CorreoRechazoMintic-Mintic", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoRemitente", @"soporte.tesamerica@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoResumenTecnico", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosAlertaCancelaciones", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosAlertaCesionExpediente", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosAlertaCesionRedes", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosAletaBloqueoGarantias", @"andres.rodriguez@tesamerica.com.co,garantias@g.com", null),
                DynamicText.Create(@"CorreosAletaBloqueoRUTIC", @"andres.rodriguez@tesamerica.com.co,rutic@g.com", null),
                DynamicText.Create(@"CorreosAletaBloqueos", @"andres.rodriguez@tesamerica.com.co,bloqueos@g.com", null),
                DynamicText.Create(@"CorreosCargaCT", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosCopiaOcultaRechazoSolicitud", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosCreacionPSO", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosDesmarcacionLocalidad", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosDocumentosRequeridosCoordinador", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosDocumentosRequeridosCoordinadorANE", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosMarcacionLocalidad", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosRadicacionSolicitudesPSO", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosRechazoSolicitudANE", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosRechazoSolicitudMINTIC", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosRequerimientoTotalBB", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosSubasanacionANE", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosSubsanacionOperador", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreosSubsanacionOperadorCopiaOculta", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"CorreoTesamerica", @"soporte.tesamerica@tesamerica.com.co", null),
                DynamicText.Create(@"Cronograma", @"2", null),
                DynamicText.Create(@"CuadroNacionalAtribucionesFrecuenciaLink", @"http://www.mintic.gov.co/images/documentos/espectro_radioelectrico/cuadro_nacional/cuadro_nacional_atribucion_bandas_de_frecuencias_2010.pdf", null),
                DynamicText.Create(@"CustomerFrontContactInfo", @"Para dudas o inquietudes respecto a la funcionalidad de esta aplicación", null),
                DynamicText.Create(@"CustomerFrontLegalInfo", @"Es interés del Ministerio de Tecnologías de la Información y las Comunicaciones (TIC) la salvaguardia de la privacidad de la información personal del usuario obtenida a través del sitio web", null),
                DynamicText.Create(@"CustomerFrontProcessInfo", @"El Sistema para la Gestión del Espectro Radioeléctrico “SGE”", null),
                DynamicText.Create(@"DependenciaAlfa", @"sage001", null),
                DynamicText.Create(@"DestinatariosBCCDesestimientoTacitoSatelital", @"soporte.sge@tesamerica.com.co", null),
                DynamicText.Create(@"DestinatariosCCDesestimientoTacitoSatelital", string.Empty, null),
                DynamicText.Create(@"DestinatariosDesestimientoTacitoSatelital", @"hernan.palta@tesamerica.com.co", null),
                DynamicText.Create(@"DestinatariosDesestimientoTacitoSatelitalpreliminarAne", @"hernan.palta@tesamerica.com.co", null),
                DynamicText.Create(@"DiasRevisionRadicadosAlfa", @"30", null),
                DynamicText.Create(@"DireccionAne", @"Calle 93B # 16-47", null),
                DynamicText.Create(@"DireccionMensajeFormato", @"El formato para ingresar la dirección de la estación en el anexo es: Identificación de la vía (calle", null),
                DynamicText.Create(@"DireccionMensajeMaximoCaracteres", @"En el anexo solo se pueden ingresar máximo 49 caracteres en la dirección de la estación.", null),
                DynamicText.Create(@"DireccionMintic", @"Edificio Murillo Toro Cra. 8a entre calles 12 y 13", null),
                DynamicText.Create(@"EmailAnalisisAdministrativo", @"soporte.tesamerica@tesamerica.com.co", null),
                DynamicText.Create(@"EmailAnalisisTecnico", @"soporte.tesamerica@tesamerica.com.co", null),
                DynamicText.Create(@"EmailAne1", @"soporte.tesamerica@tesamerica.com.co", null),
                DynamicText.Create(@"EmailAne2", @"No disponible", null),
                DynamicText.Create(@"EmailCierre", @"soporte.tesamerica@tesamerica.com.co", null),
                DynamicText.Create(@"EmailFinalizada", @"soporte.tesamerica@tesamerica.com.co", null),
                DynamicText.Create(@"EmailMintic1", @"soporte.tesamerica@tesamerica.com.co", null),
                DynamicText.Create(@"EmailMintic2", @"No disponible", null),
                DynamicText.Create(@"EmailsNotificacionSubsanarDocumentos", @"soporte.tesamerica@tesamerica.com.co", null),
                DynamicText.Create(@"EntornoPruebas", @"1", null),
                DynamicText.Create(@"EsPrueba", @"true", null),
                DynamicText.Create(@"EspTemp_AZDigital_Dependencia", @"Pru", null),
                DynamicText.Create(@"EspTemp_AZDigital_IdDirectorio", @"6369", null),
                DynamicText.Create(@"EspTemp_AZDigital_Sitio", @"Prue", null),
                DynamicText.Create(@"EspTemp_AZDigital_TramiteRadicado", @"PQRSD", null),
                DynamicText.Create(@"EspTemp_AZDigital_TramiteRegistro", @"rs", null),
                DynamicText.Create(@"EspTemp_ClaseExpediente", @"90", null),
                DynamicText.Create(@"EspTemp_CorreoAprobacionANE_MINTIC", @"solicitudesane@g.com,ruben.zuleta@tesamerica.com.co", null),
                DynamicText.Create(@"EspTemp_CorreoAprobacionMINTIC-ANE", @"Solicitudesdeespectro@g.com,ruben.zuleta@tesamerica.com.co", null),
                DynamicText.Create(@"EspTemp_CorreoAprobacionResolucion", @"solicitudesane@g.com,kballen@g.com,crojas@g.com,ligomez@g.com", null),
                DynamicText.Create(@"EspTemp_CorreoCopiaANE-MINTIC", @"solicitudesane@g.com", null),
                DynamicText.Create(@"EspTemp_CorreoCopiaMINTIC-ANE", @"Solicitudesdeespectro@g.com", null),
                DynamicText.Create(@"EspTemp_CorreoRadicarANE", @"Solicitudesdeespectro@g.com", null),
                DynamicText.Create(@"EspTemp_CorreoRadicarMintic", @"solicitudesane@g.com", null),
                DynamicText.Create(@"EspTemp_CorreoRechazoANE-MINTIC", @"solicitudesane@g.com", null),
                DynamicText.Create(@"EspTemp_CorreoRechazoMINTIC_ANE", @"Solicitudesdeespectro@g.com", null),
                DynamicText.Create(@"EspTemp_ExtensionArchivoPatronRadiacion", @".bmp,.gif,.heif,.heic,.jpg,.jpeg,.png,.psd,.svg,.tif,.tiff,.doc,.docx,.md,.odt,.pdf,.ppt,.pptx,.rtf,.txt,.xls,.xlsx,.7z,.rar,.zip", null),
                DynamicText.Create(@"EspTemp_Fecha_Subsanacion_Admin", @"1", null),
                DynamicText.Create(@"EspTemp_Fecha_Subsanacion_Tec", @"1", null),
                DynamicText.Create(@"EspTemp_Hojas_Archivo_Tecnico", @"1. Admin,2. Info General,3. IMT o PMP,4. Punto a Punto,5. Control de Cambios,Menu", null),
                DynamicText.Create(@"EspTemp_PortadaANE", @"Agencia Nacional del Espectro;Solicitudesdeespectro@g.com", null),
                DynamicText.Create(@"EspTemp_PortadaMINTIC", @"Ministerio de Tecnologías de la Información y las Comunicaciones; solicitudesane@g.com", null),
                DynamicText.Create(@"EspTemp_PuntajeTramite", @"50", null),
                DynamicText.Create(@"EspTemp_TextoReqPorAnexoTec", @"Anexo Técnico para permisos temporales: Para agilizar la evaluación técnica de la solicitud en curso", null),
                DynamicText.Create(@"EspTemp_VersionFormatoAnexo", @"1,1", null),
                DynamicText.Create(@"EstadosExpedienteActivo", @"eAUT", null),
                DynamicText.Create(@"EstadosExpedienteDatosContacto", @"eREG", null),
                DynamicText.Create(@"EstadosExpedienteMuerto", @"eX0,eX1,eX1B,eX2B,eX3,eX4,eX4B", null),
                DynamicText.Create(@"EstadosExpedienteNoUsadosCesion", @"eRES,eCT,eBDU,eDEP,eIN,eREG,eVEN,eTER,eX0,eX1,eX1B,eX2B,eX3,eX4,eX4B", null),
                DynamicText.Create(@"EstadosExpedienteNoUsadosFueraPSO", @"eVEN,eX0,eX1,eX1B,eX2B,eX3,eX4,eX4B", null),
                DynamicText.Create(@"EstadosExpedienteNoUsadosPSO", @"eCT,eRES,eVEN,eX0,eX1,eX1B,eX2B,eX3,eX4,eX4B", null),
                DynamicText.Create(@"EstadosExpedienteRadicacionParalelo", @"eAUT,eSOL", null),
                DynamicText.Create(@"EstadosExpedienteRadicacionSerie", @"eRES,eCT", null),
                DynamicText.Create(@"EstadosExpedienteSincronizacion", @"eAUT", null),
                DynamicText.Create(@"EstadosRedesSolicitudCanFrecBB", @"rAUT", null),
                DynamicText.Create(@"EstadosRedesVAC", @"rAUT,rRES,rPRN,rPRE,rTT", null),
                DynamicText.Create(@"ExcelAutoliquidador", @"Use el botón 'Cargar formato excel' si desea liquidar múltiples redes mediante un archivo .xls previamente diligenciado. El formato puede obtenerse haciendo clic en el botón 'Plantilla formato excel'", null),
                DynamicText.Create(@"ExplanationAdicionarObservacion", @"Por favor ingrese la razón por la cual realizó este cambio", null),
                DynamicText.Create(@"ExplanationAdministrationGrid", @"En esta sección podrá consultar o crear antenas y equipos y consultar reportes sobre información técnica y administrativa", null),
                DynamicText.Create(@"ExplanationAntennaCreation", @"Formulario de creación de antena", null),
                DynamicText.Create(@"ExplanationAntennaList", @"Seleccione la antena desde la lista de selección para ver los detalles. Si la antena no se encuentra puede crearla haciendo clic en el botón 'Nueva antena'", null),
                DynamicText.Create(@"ExplanationApplicationAdministrativeAnalysis", @"El análisis administrativo de una solicitud es el primer proceso luego de su radicación.", null),
                DynamicText.Create(@"ExplanationApplicationCertificados", @"Por favor seleccione el tipo de certificado", null),
                DynamicText.Create(@"ExplanationApplicationClosing", @"Las solicitudes en cierre se encuentran en proceso de generación de la resolución", null),
                DynamicText.Create(@"ExplanationApplicationCreation", @"Por favor ingrese la información requerida para crear una nueva solicitud", null),
                DynamicText.Create(@"ExplanationApplicationCreationPortfolio", @"Debe hacer una solicitud por expediente y la documentación debe corresponder al expediente que está tramitando.", null),
                DynamicText.Create(@"ExplanationApplicationDetails", @"Información básica de la solicitud", null),
                DynamicText.Create(@"ExplanationApplicationDetailsAnexarArchivos", @"Señor usuario", null),
                DynamicText.Create(@"ExplanationApplicationDetailsAnexarArchivosFuncionario", @"Señor funcionario", null),
                DynamicText.Create(@"ExplanationApplicationDetailsArchivosSolDirectas", @"Archivos necesarios: Cédula de ciudadanía", null),
                DynamicText.Create(@"ExplanationApplicationDetailsEditarInfoTecnica", @"Señor usuario", null),
                DynamicText.Create(@"ExplanationApplicationDetailsEditarInfoTecnicaFuncionario", @"Señor funcionario", null),
                DynamicText.Create(@"ExplanationApplicationDetailsRadicar", @"Señor usuario", null),
                DynamicText.Create(@"ExplanationApplicationDetailsRadicarFuncionario", @"Señor funcionario", null),
                DynamicText.Create(@"ExplanationApplicationEdit", @"Puede asignar un nombre personalizado a esta solicitud", null),
                DynamicText.Create(@"ExplanationApplicationFileList", @"A continuación se listan los archivos adjuntos a la solicitud seleccionada.", null),
                DynamicText.Create(@"ExplanationApplicationFileUpload", @"Aliste los siguientes documentos: Formato básico de solicitud", null),
                DynamicText.Create(@"ExplanationApplicationInProccess", @"Se listan las solicitudes que aún no han sido radicadas oficialmente en el sistema.", null),
                DynamicText.Create(@"ExplanationApplicationInProccessFront", @"Se listan las solicitudes que aún no han sido radicadas oficialmente en el sistema.", null),
                DynamicText.Create(@"ExplanationApplicationMessageListSummaryNoNotes", @"No se encontraron anotaciones.", null),
                DynamicText.Create(@"ExplanationApplicationRedes", @"Por favor seleccione las redes del expediente seleccionado que desea incluir en el certificado.", null),
                DynamicText.Create(@"ExplanationApplicationSolve", @"Consulte el histórico de las solicitudes finalizadas", null),
                DynamicText.Create(@"ExplanationApplicationTechnicalAnalysis", @"En el análisis técnico se efectuará un estudio detallado de la información técnica registrada para cada solicitud", null),
                DynamicText.Create(@"ExplanationDuplexerCreation", @"Formulario de creación de duplexor", null),
                DynamicText.Create(@"ExplanationDuplexerList", @"Seleccione el duplexor desde la lista de selección para ver los detalles. Si el duplexor no se encuentra puede crearlo haciendo clic en el botón 'Nuevo duplexor'", null),
                DynamicText.Create(@"ExplanationEquipmentCreation", @"Formulario de creación de equipo", null),
                DynamicText.Create(@"ExplanationEquipmentList", @"Para el caso de monitores de modulación y monitor de frecuencia y la línea de transmisión en las redes de radiodifusión sonora (AM", null),
                DynamicText.Create(@"ExplanationFilesSummaryNoFiles", @"No se han adjuntado archivos a la solicitud.", null),
                DynamicText.Create(@"ExplanationPortfolioEdit", @"Desde este formulario es posible modificar el nombre del expediente correspondiente al expediente seleccionado", null),
                DynamicText.Create(@"ExplanationPortfolioGrid", @"Listado de expedientes. Utilice los íconos frente a cada expediente para observar los detalles o editar. Si no encuentra el número de expediente deseado", null),
                DynamicText.Create(@"ExplanationRejectApplication", @"Por favor ingrese la información requerida para rechazar la solitud", null),
                DynamicText.Create(@"ExplanationSimulacionSpectrumE", @"Ingrese a esta opción si desea simular algún enlace usando el Sistema de Simulación en Línea.", null),
                DynamicText.Create(@"ExplanationTechnicalInformationEdit", @"Información general y creación de antenas", null),
                DynamicText.Create(@"ExplanationTechnicalInformationIndex", @"Visualización de la información técnica de la solicitud", null),
                DynamicText.Create(@"ExplanationTechnicalInformationSummaryNoInfo", @"No se ha ingresado información técnica a la solicitud.", null),
                DynamicText.Create(@"FaxAne", @"2436212", null),
                DynamicText.Create(@"FaxMintic", @"No disponible", null),
                DynamicText.Create(@"Fecha_Subsanacion_Coordinador_Satelital_Administrativo", @"1", null),
                DynamicText.Create(@"Fecha_Subsanacion_Coordinador_Satelital_Tecnico", @"5", null),
                DynamicText.Create(@"Fecha_Subsanacion_Revisor_Satelital_Administrativo", @"1", null),
                DynamicText.Create(@"Fecha_Subsanacion_Revisor_Satelital_Tecnico", @"10", null),
                DynamicText.Create(@"FechaFinMantenimiento", @"11/10/2023 23:00:00.000", null),
                DynamicText.Create(@"FechaInicioMantenimiento", @"11/10/2023 20:00:00.000", null),
                DynamicText.Create(@"FilesNeededToRadicate", @"los tipos de archivos obligatorios para radicar una solicitud en un proceso de selección objetiva son: Formato Básico de la Solicitud (firmado por el representante legal)", null),
                DynamicText.Create(@"FilesSummaryFilesCount", @"Número de archivos adjuntos:", null),
                DynamicText.Create(@"FirmaElectronicaAction", @"urn:/#NewOperation", null),
                DynamicText.Create(@"FirmaElectronicaAZAplicativo", @"20201209-092929-982602-00332255", null),
                DynamicText.Create(@"FirmaElectronicaAZCodificacion", @"Base64", null),
                DynamicText.Create(@"FirmaElectronicaAZContraseña", @"b1a8262799b1746913b4476ab1b17238", null),
                DynamicText.Create(@"FirmaElectronicaAZCuenta", @"20201120-151412-85f600-89728214", null),
                DynamicText.Create(@"FirmaElectronicaAZEstado", @"1-P", null),
                DynamicText.Create(@"FirmaElectronicaAZGrupo", @"20211007-161726-6bbb98-36629518", null),
                DynamicText.Create(@"FirmaElectronicaAZOrden", @"0", null),
                DynamicText.Create(@"FirmaElectronicaAZRol", @"F", null),
                DynamicText.Create(@"FirmaElectronicaAZTipoFirma", @"E", null),
                DynamicText.Create(@"FirmaElectronicaAZTipoMime", @"application/pdf", null),
                DynamicText.Create(@"FirmaElectronicaAZTipoPDF", @"PDF", null),
                DynamicText.Create(@"FirmaElectronicaAZUsuario", @"20201209-092929-982602-00332255", null),
                DynamicText.Create(@"FirmaElectronicaNombre", @"Prueba Documento AZSign PHP WS", null),
                DynamicText.Create(@"FirmaElectronicaRefWebHook", @"AZDigital: (5)", null),
                DynamicText.Create(@"FirmaElectronicaUrl", @"https://azsign.analitica.com.co/WebServices/SOAP/", null),
                DynamicText.Create(@"Garantia_Coordinador", @"Coordinador del Grupo Interno de Trabajo Gestión de Garantías", null),
                DynamicText.Create(@"Garantia_Director", @"Director de Industria de Comunicaciones", null),
                DynamicText.Create(@"Garantia_Subdirector", @"Subdirector de Industria de Comunicaciones", null),
                DynamicText.Create(@"GraficaNacionalAtribucionesFrecuenciaLink", @"http://www.mintic.gov.co/images/documentos/espectro_radioelectrico/cuadro_nacional/grafico_cuadro_nacional.pdf", null),
                DynamicText.Create(@"GrandTypeRUES", @"password", null),
                DynamicText.Create(@"HeaderRUES", @"CO-QA/GOB/MINTIC-0012/SISCD", null),
                DynamicText.Create(@"http://www.mintic.gov.co/", @"http://www.mintic.gov.co/", null),
                DynamicText.Create(@"IdExpedienteIMT", @"70974", null),
                DynamicText.Create(@"IMT_AZDigital_Dependencia", @"2.2", null),
                DynamicText.Create(@"IMT_AZDigital_IdDirectorio", @"132082", null),
                DynamicText.Create(@"IMT_AZDigital_Sitio", @"TL", null),
                DynamicText.Create(@"IMT_AZDigital_TramiteRadicado", @"PQRSD", null),
                DynamicText.Create(@"IMT_AZDigital_TramiteRegistro", @"RPTA_N", null),
                DynamicText.Create(@"IMT_CorreoRadicarMinticyANE", @"Solicitudesdeespectro@g.com,juan.benavides@tesamerica.com.co,dircom@g.com", null),
                DynamicText.Create(@"IMT_IdAntenna", @"27374", null),
                DynamicText.Create(@"IMT_IdEquip", @"17363", null),
                DynamicText.Create(@"IMT_RadioBusquedaMetros", @"2600", null),
                DynamicText.Create(@"IMT_Temp_File", @"C:\SAGE\CargueIMT\IMT_Back\tempdatafile", null),
                DynamicText.Create(@"LegendCantFilegApplicationDetails", @"Información faltante para radicar la solicitud", null),
                DynamicText.Create(@"LegendFilingApplicationDetails", @"Radicación de la solicitud", null),
                DynamicText.Create(@"LegendSpectrumE", @"Sistema de Simulación", null),
                DynamicText.Create(@"LogonMessage", @"Escriba su usuario y contraseña de Registro TIC", null),
                DynamicText.Create(@"LogonMessageAdic", @"o envíe un correo a minticresponde@mintic.gov.co", null),
                DynamicText.Create(@"LogonMessageFront", @"Señor funcionario", null),
                DynamicText.Create(@"MailDesarrolladorModuloResolucionesSinGarantia", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"MailRevisorModuloResolucionesSinGarantia", @"andres.rodriguez@tesamerica.com.co", null),
                DynamicText.Create(@"MailSmtpHost", @"smtp.gmail.com", null),
                DynamicText.Create(@"MailSmtpPassword", @"Tesamerica123*", null),
                DynamicText.Create(@"MailSmtpPort", @"587", null),
                DynamicText.Create(@"MailUsername", @"Soporte Tesamerica", null),
                DynamicText.Create(@"MainPattern", @"[ .;,:¿?¡!(){}&%$_*+\'''#|=º^¨~-]", null),
                DynamicText.Create(@"MainPatternAddress", @"[a-z .;,:ñ¿?¡!(){}&%$_*+\'@''/\\#|=º^¨~-]", null),
                DynamicText.Create(@"MainPatternRazonSocial", @"[^a-z]", null),
                DynamicText.Create(@"MensajeAdvertenciaCartera", @"Señor usuario", null),
                DynamicText.Create(@"MensajeAdvertenciaGarantias", @"Señor usuario", null),
                DynamicText.Create(@"MensajeAdvertenciaRTIC", @"Señor usuario", null),
                DynamicText.Create(@"MensajeAdvertenciaRTICDiferenciasNOPSO", @"Señor usuario", null),
                DynamicText.Create(@"MensajeAdvertenciaRTICDiferenciasPSO", @"Señor usuario", null),
                DynamicText.Create(@"MensajeBloqueoCartera", @"Señor usuario", null),
                DynamicText.Create(@"MensajeBloqueoGarantias", @"Señor usuario", null),
                DynamicText.Create(@"MensajeBloqueoRTIC", @"Señor usuario", null),
                DynamicText.Create(@"MensajeCrearExpediente", @"<div class='nombre_campo'><p style='margin:20px; text-align:justify;'>Señor usuario:</p><br/><p style='margin:20px; text-align:justify;'>El usuario acepta que a través del registro en el sitio web", null),
                DynamicText.Create(@"MensajeDuranteMantenimiento", @"El Ministerio de Tecnologías de la Información/Fondo Único de TIC informa que se encuentra realizando un mantenimiento al aplicativo desde <u>las {0} hasta las {1} Durante este mantenimiento los servicios no están disponibles.</u> Agradecemos su comprensión.", null),
                DynamicText.Create(@"MensajeInfoEmergenciaSeguridad", @"Las solicitudes que se realizan en esta sección se encuentran exceptuadas del procedimiento de selección objetiva", null),
                DynamicText.Create(@"MensajeInfoNOPSO", @"Las solicitudes que se realizan en esta sección corresponden a las que pueden ser tramitadas fuera de un Proceso de Selección Objetiva- PSO", null),
                DynamicText.Create(@"MensajeInfoPSOP1", @"Las solicitudes que se realizan en esta sección deben ser tramitadas bajo un Proceso de Selección Objetiva- PSO", null),
                DynamicText.Create(@"MensajePrevioMantenimiento", @"El Ministerio de Tecnologías de la Información/Fondo Único de TIC informa que el próximo <b>{0} hasta las {1}</b> realizara mantenimiento al aplicativo. <b>Durante este mantenimiento los servicios no estarán disponibles.</b> Agradecemos su comprensión no ingresando a la aplicación en esta franja de tiempo.", null),
                DynamicText.Create(@"MetodoEnvioAlfa", @"TL", null),
                DynamicText.Create(@"MotivoRechazoCartera", @"No cumplir con lo establecido en el numeral 2 del artículo 3 de la resolución 485 de 2024", null),
                DynamicText.Create(@"MotivoRechazoGarantias", @"No cumplir con lo establecido en el numeral 3 del artículo 3 de la resolución 485 de 2024", null),
                DynamicText.Create(@"MotivoRechazoRUTIC", @"No cumplir con lo establecido en el numeral 1 del artículo 3 de la resolución 485 de 2024", null),
                DynamicText.Create(@"NaturalezaAlfaSolicitud", @"100", null),
                DynamicText.Create(@"NitAne", @"9003342653", null),
                DynamicText.Create(@"NitMintic", @"89999953-1", null),
                DynamicText.Create(@"NombreAne", @"Agencia Nacional del Espectro", null),
                DynamicText.Create(@"NombreArchivoAlfaAnalisisAdministrativo", @"Registro_Fin_Analisis_Administrativo_Solicitud_{0}_{1:ddMMyyHHmmss}.rtf", null),
                DynamicText.Create(@"NombreArchivoAlfaAnalisisTecnico", @"Aprobacion_Tecnica_Solicitud_{0}_{1:ddMMyyHHmmss}.rtf", null),
                DynamicText.Create(@"NombreArchivoAlfaClosing", @"Aprobacion_Final_Solicitud_{0}_{1:ddMMyyHHmmss}.rtf", null),
                DynamicText.Create(@"NombreArchivoAlfaRadicacion", @"Radicacion_Solicitud_{0}_{1:ddMMyyHHmmss}.xml", null),
                DynamicText.Create(@"NombreArchivoAlfaRadicarArchivo", @"Radicación_Archivo_Solicitud_{0}_{1:ddMMyyHHmmss}.rtf", null),
                DynamicText.Create(@"NombreArchivoAlfaRechazoSolicitud", @"Rechazo_Solicitud_{0}_{1:ddMMyyHHmmss}.pdf", null),
                DynamicText.Create(@"NombreMintic", @"Ministerio TIC", null),
                DynamicText.Create(@"NumeroArchivosRadicacion", @"2", null),
                DynamicText.Create(@"NumeroArchivosRadicacionSolDirecta", @"9", null),
                DynamicText.Create(@"PaginaMinisterio", @"http://www.mintic.gov.co/", null),
                DynamicText.Create(@"PasswordAlfa", @"0qLpWZIlpg2zlKSYcj0D", null),
                DynamicText.Create(@"PasswordRUES", @"k272ki8bLnLpFK7aUuUEzw==", null),
                DynamicText.Create(@"PasswordServicioAuraPortalNew", @"1mp3rs0n4t3.", null),
                DynamicText.Create(@"PointToPointAndPointToMultipointExplanation", @"Si por algún motivo", null),
                DynamicText.Create(@"RequiredFieldImageMessage", @"Campo requerido", null),
                DynamicText.Create(@"Resolucion", @"485 de 2024", null),
                DynamicText.Create(@"ResumenTecnicoTexto", @"En virtud de la(s) solicitud(es) de [TipoTramite_NumRadicado]", null),
                DynamicText.Create(@"RolesPermisoModuloResoluciones", @"1,2,3,4,5,6,7,10,21,22,30,57,59,60,61,62,72,73,74,75,76,77,78,79,98,99,100,101,107,108", null),
                DynamicText.Create(@"RolesPermisoRevisionOficio", @"73,74,75,101,107", null),
                DynamicText.Create(@"RolesPermisoRevisionResoluciones", @"2,3,4,5,6,7,22,57,59,60,61,62,76,77,78,79,99,100,108", null),
                DynamicText.Create(@"RolesPermisoVerDocumentacionSolicitudesDirectas", @"30,76,77,78,79,57,59,98,60,61,62,99,100,72,73,74,75,101,107,108", null),
                DynamicText.Create(@"RutaGetConsultaRUES", @"wsConsultaRUES", null),
                DynamicText.Create(@"RutaGetTokenRUES", @"wsToken", null),
                DynamicText.Create(@"Satelital_CorreoFinResolucionMINTIC", @"ebernate@g.com,kballen@g.com,carengifo@g.com,crojas@g.com,aruiz@g.com,nmendez@g.com", null),
                DynamicText.Create(@"Satelital_FirmaElec_Director", @"dreinales", null),
                DynamicText.Create(@"Satelital_FirmaElec_SubDirector", @"lpineda", null),
                DynamicText.Create(@"Satelital_Portada_ANE", @"Agencia Nacional del Espectro;Solicitudesdeespectro@g.com", null),
                DynamicText.Create(@"Satelital_Portada_MINTIC", @"Ministerio de Tecnologías de la Información y las Comunicaciones; solicitudessatelital@g.com", null),
                DynamicText.Create(@"SerieDocumentalAlfa", @"100", null),
                DynamicText.Create(@"SolFisicaDiasAdicionalFechaVenc", @"60", null),
                DynamicText.Create(@"Subdireccion_Industria", @"gperdomo@mintic.gov.co", null),
                DynamicText.Create(@"SubdirectorIndustria", @"gperdomo", null),
                DynamicText.Create(@"SubdirectorPSO", @"gperdomo", null),
                DynamicText.Create(@"SystemDescription", @"El Sistema para la Gestión del Espectro Radioeléctrico “SGE” permite a los titulares de permiso para el uso del espectro tramitar ante el Ministerio de Tecnologías de la Información y las Comunicaciones", null),
                DynamicText.Create(@"TechnicalInformationSummaryNetworkCount", @"Número de redes de la solicitud:", null),
                DynamicText.Create(@"TechnicalInformationSummaryNetworkNumber", @"Red número:", null),
                DynamicText.Create(@"TechnicalInformationSummaryXmlMassivelyUploaded", @"Información cargada masivamente a partir de archivo .xml", null),
                DynamicText.Create(@"TelefonoAne1", @"3442299", null),
                DynamicText.Create(@"TelefonoAne2", @"No disponible", null),
                DynamicText.Create(@"TelefonoMintic1", @"3443460", null),
                DynamicText.Create(@"TelefonoMintic2", @"No disponible", null),
                DynamicText.Create(@"Temp_File_Espectro_New", @"C:\SAGE\EspectroTemporal\EspectroTemp_Back\tempdatafile", null),
                DynamicText.Create(@"Temp_File_EspectroTemporal", @"C:\SAGE\EspectroTemporal\EspectroTemp_Back\tempdatafile", null),
                DynamicText.Create(@"Temp_File_Satelital", @"C:\SAGE\SGE\tempdatafile", null),
                DynamicText.Create(@"Temp_File_Satelital_New", @"C:\SAGE\Satelital\Satelital_Back\tempdatafile", null),
                DynamicText.Create(@"TermsAndConitions", @"Términos y condiciones: como usuario de la aplicación", null),
                DynamicText.Create(@"TextoDetalleAlfaAnalisisAdministrativo", @"Notificación de Aprobación de Análisis Administrativo de la Solicitud: {0}", null),
                DynamicText.Create(@"TextoDetalleAlfaAnalisisTecnico", @"Notificación de Aprobación de Análisis Técnico de la Solicitud: {0}", null),
                DynamicText.Create(@"TextoDetalleAlfaClosing", @"Notificación de Aprobación final de la Solicitud: {0}", null),
                DynamicText.Create(@"TextoDetalleAlfaRadicacion", @"Radicación de la Solicitud: {0}", null),
                DynamicText.Create(@"TextoDetalleAlfaRadicarArchivo", @"Notificación de Radicación de Archivo  de la Solicitud: {0}", null),
                DynamicText.Create(@"TextoDetalleAlfaRechazoSolicitud", @"Notificación de Rechazo de la Solicitud: {0}", null),
                DynamicText.Create(@"TextoFirmaCertificadoEspectro", @"Asesora del Despacho del Viceministerio de Transformación Digital encargada de las funciones del Subdirector para la Industria de Comunicaciones", null),
                DynamicText.Create(@"TextoNotificacionSigpol", @"Señor usuario una de sus garantías presenta una novedad", null),
                DynamicText.Create(@"TextoRefRadicadoAnalisisTecnico", @"Resultado de Análisis Técnico de la Solicitud con radicado MINTIC No. {0} del {1}.", null),
                DynamicText.Create(@"TextoRefRegistroAnalisisAdministrativo", @"Traslado para Análisis Técnico de la Solicitud con radicado No. {0} del {1}.", null),
                DynamicText.Create(@"TiempoAutoguardadoMilisegundos", @"300000", null),
                DynamicText.Create(@"TiempoTokenMatrizANE", @"50000", null),
                DynamicText.Create(@"TiposResolucionRenovacionOtorga", @"1", null),
                DynamicText.Create(@"TokenTMP_Email", @"soporte.sge@mintic.gov.co", null),
                DynamicText.Create(@"TokenTMP_Rol", @"128", null),
                DynamicText.Create(@"TokenTMP_SecretKey", @"F4209FA7-FAF6-4BF0-8A5E-783BE439DF9E", null),
                DynamicText.Create(@"TokenTMP_TypeIdent", @"NIT", null),
                DynamicText.Create(@"TokenTMP_User", @"Sistema de Gestión del Espectro", null),
                DynamicText.Create(@"UbicacionDocumentosSGE", @"C:\SAGE\DocumentosSGE\", null),
                DynamicText.Create(@"UrlImportSpectrumE", @"http://simulacion.ane.gov.co:8088/se/portal/ane/loginproc.php?", null),
                DynamicText.Create(@"UrlLoginSpectrumE", @"http://simulacion.ane.gov.co:8088/se/portal/ane/loginproc.php?", null),
                DynamicText.Create(@"UserAlfa", @"usersage", null),
                DynamicText.Create(@"UsernameRUES", @"UserMinTic", null),
                DynamicText.Create(@"UsuarioServicioAuraPortalNew", @"mintic/bpmimpersonate", null),
                DynamicText.Create(@"VersionFormatosAnexos_Satelital", @"V1.4", null),
                DynamicText.Create(@"WfTipoAlfa", @"0", null),
                DynamicText.Create(@"WfTipoAlfaInterno", @"1", null),
                DynamicText.Create(@"xmlnsazs", @"http://www.analitica.com.co/AZSign/Esquemas", null),
                DynamicText.Create(@"xmlnsxsi", @"http://www.w3.org/2001/XMLSchema-instance", null),
                DynamicText.Create(@"xsischemaLocation", @"http://www.analitica.com.co/AZSign/Esquemas file:///F:/AZSign/Producto/AZSign/WebServices/WS-AZSign.xsd", null));
        }

    private void ApplyLinksSeeder(EntityTypeBuilder<DynamicText> builder)
    {
            builder.HasData(
                DynamicText.Create(@"AutenticacionTMP_Pruebas", @"https://pruebas.tesmonitorplanning.com/TesMonitorPlanning/TesMonitorPlanningWeb/index.html?ID=", null),
                DynamicText.Create(@"AutenticacionTMP", @"https://espectro-co.ane.gov.co/TesMonitorPlanning/TesMonitorPlanningWeb/index.html?ID=", @"https://espectro-co.ane.gov.co/TesMonitorPlanning/TesMonitorPlanningWeb/index.html?ID="),
                DynamicText.Create(@"CorreoCertificadoURL", @"https://cert-integratic.mintic.gov.co/Notificaciones/WebServices/SOAP/", @"Link consumo para el servicio de Notificaciones (IntegraTIC)"),
                DynamicText.Create(@"DocumentosSGE_URL", @"https://cert-gestion-espectro.mintic.gov.co/DocSGE/DocSGE_Front", @"URL de documentos del SGE"),
                DynamicText.Create(@"FirmaElectronicaAZURL", @"https://azsign.analitica.com.co/WebServices/SOAP/", @"Link consumo para el servicio de firma electrónica (AZSign)"),
                DynamicText.Create(@"FlashPlayer", @"https://get.adobe.com/es/flashplayer/", @"https://get.adobe.com/es/flashplayer/"),
                DynamicText.Create(@"PrivacyPolicy", @"http://www.mintic.gov.co/index.php/privacidad-condiciones-uso", @"Ver el texto completo"),
                DynamicText.Create(@"RegistroTicUrl", @"http://www.mintic.gov.co/portal/604/w3-article-6398.html", @"Registro de TIC"),
                DynamicText.Create(@"ServicioAuraQuantic", @"https://uatbpm-integraciones.mintic.gov.co:8001/ServiciosRUTIC/api/Rutic/ConsultarDatosAdministrativos", @"Link de consumo para servicio AuraQuantic"),
                DynamicText.Create(@"ServicioRUES", @"http://10.100.101.174/r1/CO-QA/GOB/CONFECAMARAS-0001/RUES/", @"Link de consumo para el servicio RUES"),
                DynamicText.Create(@"ServicioSGE-RUES", @"http://salicaria:8749/api/rues/consultaRUES", @"Link de consumo para el servicio SGE-RUES"),
                DynamicText.Create(@"ServicioSGE-RUESLocal", @"http://192.168.0.10:8749/api/rues/consultaRUES", @"Link de consumo para el servicio SGE-RUES"),
                DynamicText.Create(@"SupportEmail", @"mailto:soporte.sge@mintic.gov.co", @"(soporte.sge@mintic.gov.co)"),
                DynamicText.Create(@"SupportEmail_Prueba", @"mailto:rsandoval@mintic.gov.co", @"rsandoval@mintic.gov.co"),
                DynamicText.Create(@"UrlFirmaElectronica", @"https://azsign.analitica.com.co/WebServices/SOAP/", @"URL de consumo para el servicio de firma electrónica"));
    }
}